### ISSUE TITLE
Server sends incorrect Enderman holding item on 1.9, 1.10, 1.11

### ISSUE THREAD

**Issue by KernelFreeze** [MylesIsCool/ViaVersion#580] opened 2016-11-21 23:52 UTC
### What is the output link of /viaversion dump? 
http://hastebin.com/unilazocew.json and our test server: http://hastebin.com/ebudinihif.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
I'm using Waterfall 1.8-1.11.

### How does this error happen? login? Using an item? 
When I summon an Enderman in 1.8.x with "/summon Enderman ~ ~ ~ {carried:1}" it works fine, but if I join my server with any version > 1.9, the enderman holds a incorrect block (it should be stone, but it's coal ore).
http://imgur.com/a/BpYZf

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Nope

**Comment by MylesIsCool** [comment] 2016-11-28 23:14
Confirmed bug, seems to be bitshifted wrong.

**Comment by MylesIsCool** [comment] 2016-11-28 23:48
Fixed in latest dev

**Closed by MylesIsCool** 2016-11-28 23:48 UTC
Labels: Bug
