### ISSUE TITLE
json disconnect error version 0.4.5

### ISSUE THREAD

**Issue by cloakfox** [MylesIsCool/ViaVersion#78] opened 2016-03-03 09:46 UTC
Hello, I am on ViaVersion 0.4.5 and now when I try to join my server
wich is on latest 1.8.8 build
`[04:59:12 INFO]: This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[04:59:12 INFO]: Checking version, please wait...
[04:59:12 INFO]: You are 68 version(s) behind
`
I get this json error on my 1.9 client and this error in console: 
`[04:58:31 WARN]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
io.netty.handler.timeout.ReadTimeoutException
[04:58:31 INFO]: cloakfox lost connection: Disconnected
`

Also a list of my plugins:
`[04:58:05 INFO]: Plugins (15): icJukeBox, WorldEdit, PermissionsEx, Buycraft, ViaVersion, Vault, ProtocolLib, WorldGuard, BetterDrops, AgarioMC, NoCheatPlus, Essentials, EssentialsChat, EssentialsSpawn, EssentialsProtect
`

**Comment by HugoDaBosss** [comment] 2016-03-03 09:51
First of all, there is a newer spigot version: git-Spigot-e4d4710-e1ebe52
And how do you know this is caused by json? 
The error looks similar to https://github.com/MylesIsCool/ViaVersion/issues/68 Can you confirm?

**Comment by cloakfox** [comment] 2016-03-03 09:53
I don't know, I honestly think my issue is related to being incompatible with a certain plugin.
Still would be great if this plugin supported as much as it could.

**Comment by HugoDaBosss** [comment] 2016-03-03 09:58
The JSON error could be fixed by https://github.com/MylesIsCool/ViaVersion/pull/77 , or atleast you can see what string causes this.

**Comment by MylesIsCool** [comment] 2016-03-03 10:13
This error is just simply a replication of disconnect our. Due to the way our plugin works it happens to throw errors twice.

**Comment by MylesIsCool** [comment] 2016-03-03 10:14
Going to close this as this is technically a duplicate of #68

**Closed by MylesIsCool** 2016-03-03 10:14 UTC
