### ISSUE TITLE
Players cannot join serveur with 1.9/1.9.2 clients

### ISSUE THREAD

**Issue by HarryBeau28** [MylesIsCool/ViaVersion#621] opened 2017-01-19 12:31 UTC
### What is the output link of /viaversion dump? 

https://gist.github.com/30c8fb0aef05b1df256685b40d8a63af

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

Latest build of ViaVersion for my 1.9..4 spigot serveur
ProtocolSupport for backward compatibilities

### How does this error happen? login? Using an item? 

When a 1.9 or 1.9.2 player tries to join server he's instantly kick.

### Is there an error in the console? Use pastebin.com. Is there a kick message?

[13:26:11] [Server thread/INFO]: HarryBeau28[/hidden] logged in with entity id 1978 at ([Hub]12.5, 23.0, -18.5)

[13:26:11] [Craft Scheduler Thread - 33/WARN]: [Fatal Error] :1:1: Fin prématurée du fichier.

[13:26:11] [Server thread/INFO]: HarryBeau28 lost connection: Internal Exception: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/MylesIsCool/ViaVersion/issues

{Type: Chunk, Source #1: us.myles.ViaVersion.protocols.protocol1_9_1_2to1_9_3_4.Protocol1_9_1_2TO1_9_3_4$2 (Anonymous), Source #0: us.myles.ViaVersion.protocols.protocol1_9_1_2to1_9_3_4.Protocol1_9_1_2TO1_9_3_4$2$1 (Anonymous), Data: [], Packet ID: 32}

**Comment by MylesIsCool** [comment] 2017-01-19 14:43
Duplicate of #615

**Closed by MylesIsCool** 2017-01-19 14:43 UTC
