### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Yive** [MylesIsCool/ViaVersion#5] opened 2016-02-29 20:29 UTC
## PaperSpigot

Version:This server is running CraftBukkit version git-PaperSpigot-"a861cc6" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Console: https://i.tcpr.ca/xBkx065
Client: https://i.tcpr.ca/kWhSSS4
Plugins: https://i.tcpr.ca/0ZDKnsa

## Spigot

Version: This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Console: https://i.tcpr.ca/gLCTgrm
Client: https://i.tcpr.ca/Nih0Chu
Plugins: https://i.tcpr.ca/0ZDKnsa

**Comment by MylesIsCool** [comment] 2016-02-29 20:43
Can you verify this still occurs in version 0.3?

**Comment by Yive** [comment] 2016-02-29 20:48
Client error still occurs, the java.lang.IndexOutOfBoundsException error does not pop up in console anymore on both softwares though. All that happens is that happens is
```
Yive lost connection: Internal Exception: java.io.IOException: Error while writev(...): Broken pipe
```

Also just realised that I am able to join the server for less than a second before AuthMe teleports me to spawn & I end up disconnecting with the error that was listed above for client side.

**Comment by danjb2000** [comment] 2016-02-29 20:48
Can vouch: http://www.lemoncloud.org/imgs/20-47-43.png

**Comment by danjb2000** [comment] 2016-02-29 20:54
21:47:39] [Async Chat Thread - #1/INFO]: <[0;31;22miLemon[m> spawn eggs are broken though[m
[21:47:42] [Netty Epoll Server IO #0/WARN]: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Byte
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at us.myles.ViaVersion.transformers.OutgoingTransformer.transformMetadata(OutgoingTransformer.java:437)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at us.myles.ViaVersion.transformers.OutgoingTransformer.transform(OutgoingTransformer.java:176)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at us.myles.ViaVersion.handlers.ViaOutboundHandler.write(ViaOutboundHandler.java:35)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:104)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at us.myles.ViaVersion.handlers.ViaOutboundPacketHandler.write(ViaOutboundPacketHandler.java:43)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[21:47:42] [Netty Epoll Server IO #0/WARN]: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Byte
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at us.myles.ViaVersion.transformers.OutgoingTransformer.transformMetadata(OutgoingTransformer.java:437)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at us.myles.ViaVersion.transformers.OutgoingTransformer.transform(OutgoingTransformer.java:176)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at us.myles.ViaVersion.handlers.ViaOutboundHandler.write(ViaOutboundHandler.java:35)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:104)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at us.myles.ViaVersion.handlers.ViaOutboundPacketHandler.write(ViaOutboundPacketHandler.java:43)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[21:47:42] [Netty Epoll Server IO #0/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[21:47:42] [Server thread/INFO]: iLemon lost connection: Disconnected
[21:47:42] [Server thread/INFO]: iLemon left the game.

**Comment by MylesIsCool** [comment] 2016-02-29 20:56
Any idea what mob causes the error given above @danjb2000? (It's a mob issue)

**Comment by danjb2000** [comment] 2016-02-29 21:02
We believe it's ghasts however the likelihood is there's more.

**Comment by Vyzon** [comment] 2016-03-01 05:52
I seem to have this same issue. The cause of mine said ARMOR_STAND so I removed all armor stands, but the error still happend it just quit saying the cause was armor stands.

**Comment by MylesIsCool** [comment] 2016-03-01 10:32
I'm aware of an issue with armour stands which should be fixed with in the next few hours (not sure if i'll release immediately on spigot due to wanting to fix more bugs first)

**Comment by MylesIsCool** [comment] 2016-03-01 10:52
@danjb2000 Any chance you can get the error on the new version as it will identify the issue?

**Comment by Vyzon** [comment] 2016-03-01 11:25
I'm pretty sure me and dan are experiencing the same issue.
Client Error: http://prntscr.com/a9s80f
Server Log: http://www.hastebin.com/apimidoxap.java

**Comment by MylesIsCool** [comment] 2016-03-01 11:26
@Vyzon What plugins are you using?

**Comment by Vyzon** [comment] 2016-03-01 11:33
Http://prnt.sc/a9saaj

**Comment by Vyzon** [comment] 2016-03-01 11:35
I did remove protocollib when I tried using viaversion (sorry) GitHub went down on my pc for some reason.

**Comment by LukvonStrom** [comment] 2016-03-01 14:10
Confirmed with no plugins on latest 1.8 Spigot

**Comment by MylesIsCool** [comment] 2016-03-01 23:37
Please open seperate issues, if you believe your error is different. Please try the latest version, gonna close this error please create a new one if it still occurs thanks!

**Closed by MylesIsCool** 2016-03-01 23:37 UTC
