### ISSUE TITLE
AAC is not compatible

### ISSUE THREAD

**Issue by ChavitaHD** [MylesIsCool/ViaVersion#72] opened 2016-03-03 04:46 UTC
When someone joins it kicks them and shows this messages:
https://paste.parallaxmc.com/puhidobapo.avrasm

**Comment by Paulomart** [comment] 2016-03-03 06:07
Which version? Is this in latest?

**Comment by ChavitaHD** [comment] 2016-03-03 06:11
latest.

**Comment by Paulomart** [comment] 2016-03-03 06:16
What plugins are you using?

**Comment by Paulomart** [comment] 2016-03-03 06:20
Is there anything before in the log?

**Comment by ChavitaHD** [comment] 2016-03-03 06:23
Nothing in the log, 
http://prntscr.com/aak0qz

**Comment by Paulomart** [comment] 2016-03-03 06:27
Remove AAC and test again it's known to cause problems

**Comment by ChavitaHD** [comment] 2016-03-03 06:28
will it be updated? I use it on all my servers.

**Comment by Paulomart** [comment] 2016-03-03 06:30
I don't know. Please see if it works. Then try talking to the author. It might be an issue with their force field detection. It's closed source and payed right?

**Comment by ChavitaHD** [comment] 2016-03-03 06:34
It is closed source.

**Comment by Paulomart** [comment] 2016-03-03 06:35
Yeah so I cannot take a look at it. Try removing

**Comment by ChavitaHD** [comment] 2016-03-03 06:35
Alright.

**Comment by ChavitaHD** [comment] 2016-03-03 06:36
I am sure it is, it only happens to others not me, so it is a perm thing, I am sure it is, I will contact the dev.

**Comment by Paulomart** [comment] 2016-03-03 06:37
Ok, it was acc? Link him this issue. Please don't close it.

**Comment by ChavitaHD** [comment] 2016-03-03 06:40
Linked him via PM.

**Comment by ridalarry** [comment] 2016-03-03 10:19
Its caused by the npcs because when I disabled forcefield checks and made killaura npcs spawn rate to 0% it was fixed

**Comment by MylesIsCool** [comment] 2016-03-03 10:42
Is this a generic solution for AAC @ridalarry can I list this on the plugin page so people can have full compatibility?

**Comment by ChavitaHD** [comment] 2016-03-03 13:33
Well without the check it would default of the purpose of it being an anti chea.

**Comment by MylesIsCool** [comment] 2016-03-03 13:36
I'd suggest contacting them, as it's a paid plugin not much we can do.

**Comment by ridalarry** [comment] 2016-03-03 18:14
For me it seems fixed on my test server, but I am not using it on the main server as I don't want my players to crash, and I want to check for killaura and forcefield, so I switched to NoCheatPlus temporarly. I would recommend contacting the dev of AAC about it as he can help you find a faster solution without turning these 2 features off.

**Comment by Z609** [comment] 2016-03-03 20:26
I would probably look into this: https://github.com/aadnk/PacketWrapper/blob/master/PacketWrapper/src/main/java/com/comphenix/packetwrapper/WrapperPlayServerNamedEntitySpawn.java

That's how I create NPCs like AAC

**Comment by timr2000** [comment] 2016-03-03 22:27
i hope you found the problem and fixed it  :P, i got the same problem now.

**Comment by Z609** [comment] 2016-03-04 00:37
Hey @timr2000 and @ridalarry Try this config in forcefield

http://pastebin.com/8PSYn7ZU

It will still let players float around you but you'll still get spammed in console. Hopefully this is a temp fix.

**Comment by Aangiix3** [comment] 2016-03-08 07:17
@MylesIsCool most server owners are waiting for this fix to install it, AAC is very important

**Comment by MylesIsCool** [comment] 2016-03-08 10:42
@Aangixx that's cool, considering its a paid closed source plugin and it's stated it won't support us, why should we bother? I don't plan on buying a copy.

You can see advised settings above otherwise I don't personally plan on fixing this.

**Comment by Aangiix3** [comment] 2016-03-08 16:58
@MylesIsCool as @Z609 said it's probably about ProtocolLib and not AAC itself.

One of these NPC Stuff doesn't work:
http://pastebin.com/8PSYn7ZU

**Comment by MylesIsCool** [comment] 2016-03-08 17:41
@Aangiix3 We're not going to fix this issue. Unless you can find another publically avaliable plugin that causes the same issue, it's not going to be fixed. I don't own a copy of AAC, I don't plan to, giving me this information does not help me.

**Comment by i9hdkill** [comment] 2016-03-09 17:31
AAC is quite important (Only the npc checks) for us and probably for many other pvp based servers. Would you look into it, when you get the money for a copy?

**Comment by ridalarry** [comment] 2016-03-09 21:33
Even if they bought a version AAC code is obfuscated, so it would be hard to decompile and check it.

**Comment by MylesIsCool** [comment] 2016-03-09 21:36
See @ridalarry going to close this, Unless we have the same issue with another plugin we'll fix it and reopen this. Otherwise the code is obfuscated etc, which makes it hard and is most likely against his terms. If he wants to fix it sure, but he has stated he won't support us.

**Closed by MylesIsCool** 2016-03-09 21:36 UTC
