### ISSUE TITLE
Far (2-3 view distance) Chunk Loading in 1.9 hangs, in 1.8 works

### ISSUE THREAD

**Issue by Bodoo** [MylesIsCool/ViaVersion#107] opened 2016-03-03 21:01 UTC
In our Bedwars/Skywars Maps, you can't see the near islands of other players, but you can see the players. This is only in 1.9, in 1.8 the chunks load perfectly.

**Comment by Paulomart** [comment] 2016-03-03 21:02
Duplicate of 38

**Closed** 2016-03-03 21:27 UTC
