### ISSUE TITLE
Hologram at wrong height in 1.11

### ISSUE THREAD

**Issue by CT16** [MylesIsCool/ViaVersion#577] opened 2016-11-21 16:24 UTC
### What is the output link of /viaversion dump? 

N/A (failed to dump, don't think it's relevant?)

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

BungeeCord, latest. All plugins except Buycraft and ViaVersion are custom. They do not interact with entities in any way.

### How does this error happen? login? Using an item? 

Always, login.

### Is there an error in the console? Use pastebin.com. Is there a kick message?

No.

###Additional Information

I've got some holograms which are spawned in with a command:

> /summon armor_stand 0 70 0 {CustomName:"Hologram Text Here",CustomNameVisible:1}

And these work fine. However 99% of my holograms are now using my custom hologram maker:

            Integer lineID = -1;
            Location spawnLoc = loc;
            spawnLoc.setY(spawnLoc.getY() + distanceBetweenStands);
            ArmorStand stand = null;
            ArmorStand prevStand = null;
            for (String line : lines){
                spawnLoc.setY(spawnLoc.getY() - distanceBetweenStands);
                stand = loc.getWorld().spawn(spawnLoc, ArmorStand.class);
                stand.setRemoveWhenFarAway(false);
                stand.setVisible(false);
                stand.setSmall(true);
                stand.setBasePlate(false);
                stand.setGravity(false);
                stand.setArms(false);
                stand.setCustomNameVisible(true);
                stand.setCustomName(colorString(line));
                stands.add(stand);
                LivingEntity ent = stand;
                ent.setRemoveWhenFarAway(false);
                lineID++;

And with these holograms, they're a few blocks lower than intended, I think 2. They're fine on every other version, 1.8 - 1.10.

**Comment by Matsv** [comment] 2016-11-21 18:22
Duplicate of #564

**Closed by Matsv** 2016-11-21 18:22 UTC
