### ISSUE TITLE
/r and /tell result in kick for 1.13 clients

### ISSUE THREAD

**Issue by Castiella** [MylesIsCool/ViaVersion#913] opened 2018-07-21 21:01 UTC
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/7e97386146898ee044d7018aecd4bbc95010d044d9ad6008e0fbe80c2d35f38d

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Paper Spigot 1.12.2

### How does this error happen? login? Using an item? 

/r and /tell result in kick for spam for 1.13 clients, but /msg works.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
kicked for spam

**Comment by Matsv** [comment] 2018-07-22 01:29
Duplicate of #891

**Closed by Matsv** 2018-07-22 01:29 UTC
