### ISSUE TITLE
Glitching horses

### ISSUE THREAD

**Issue by L4BORG** [MylesIsCool/ViaVersion#781] opened 2017-11-23 21:11 UTC
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/2241b7759d876bb2bdf012f461698edf

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord with NuVotifier

### How does this error happen? login? Using an item? 
https://www.youtube.com/watch?v=f5mf3IQ4AXA
https://www.youtube.com/watch?v=A4i5K100gtc
https://www.youtube.com/watch?v=3S09Fw6rt4k

This issue is present with or without AntiCheat plugins, if plugins like NCP are present player would most likely die in ground / void. Once chunks start bugging (not rendering) that will be it, even if you can get off your horse that won't fix the issue, however rejoin would do the trick.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No.

**Comment by MylesIsCool** [comment] 2017-11-28 15:18
Are you able to replicate this issue with just ViaVersion?

**Comment by L4BORG** [comment] 2017-11-28 17:07
Yes.

![alt text](http://shrani.si/f/B/fR/3dyVKJPO/untitled.png)

**Comment by TheIntelloBox** [comment] 2017-11-28 19:19
If you have a ressource pack that's the problem.

**Comment by L4BORG** [comment] 2017-11-28 19:21
I was not using resource packs in this videos...

**Comment by TheIntelloBox** [comment] 2017-12-01 17:13
That's not ViaVersion's fault. I had this problem in solo.

**Comment by TheIntelloBox** [comment] 2018-01-03 12:17
You should close this issue.

**Comment by L4BORG** [comment] 2018-01-03 13:06
Why? I've been trying for 30 minutes now and I can't replicate this in singleplayer.

**Comment by electronicboy** [comment] 2018-01-03 13:27
if you had this problem in solo, you have really horrible issues. This is more than likely down to some form of desync between the player's position or one of the many quirks around this kinda thing in craftbukkit, you can ctrl-F3-a to force the game to re-render all of the chunks, should give some indicator if this is an odd issues with rendering or if there is some form of desync;

The fact that in one of your videos shows that there are actual blocks there, even if not visible, is a fun one which was actually a bug in 1.8.8, which I don't think has ever been properly fixed

**Comment by Matsv** [comment] 2018-01-05 22:21
Horse riding became client-sided in 1.9, we decided at the time to not implement it [(More info)](https://github.com/MylesIsCool/ViaVersion/issues/196).
I'm guessing it's not sync because of that. To confirm this: try to play with 2 clients: one client on a horse that reproduces the error, and one to analyze if you are even near the chunk that has to be loaded.

**Comment by MylesIsCool** [comment] 2018-01-08 00:00
This issue seems very complex and is very much what Mats and electronicboy said, I'd highly suggest updating (if it happens a lot) or hiring someone to look into it personally for you.

**Closed by MylesIsCool** 2018-01-08 00:00 UTC
