### ISSUE TITLE
Boats on 1.8 server move as in 1.9 with a 1.9 client

### ISSUE THREAD

**Issue by StarDan90** [MylesIsCool/ViaVersion#381] opened 2016-04-29 02:17 UTC
### What version of ViaVersion are you using? Type /ver viaversion
0.7.9
### What version of Spigot are you using? Type /ver
1.8
### What plugins are you using? Type /plugins
http://pix.toile-libre.org/upload/original/1461893351.png
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
1.9 BungeeCord. SkinsRestorer and BungeeTablistPlus
### How does this error happen? login? Using an item? 
Boats have a weird behaviour. They can crash and drop the respective items, but their movement is like in 1.9. Also, if you place them on land, travel a bit (no matter if you travel on water or land) and then quit the boat, you'll return to the place where the boat was placed, and the boat returns to you.
### Is there an error in the console? Use pastebin.com. Is there a kick message?
Nope.

**Comment by Matsv** [comment] 2016-04-29 07:02
Duplicate of #196. This issue is because mojang made in 1.9 boat/horse riding client-sided. I tried some things to make it sync, but everything i tried would make it look bad/laggy (because of 1 tick delay/ping delay) on 1.8 or 1.9. I'll close this issue because it's a duplicate, follow #196 for progress updates on this topic

**Closed** 2016-04-29 07:03 UTC
