### ISSUE TITLE
Respawn button is grayed out (non-1.8 clients)

### ISSUE THREAD

**Issue by L4BORG** [MylesIsCool/ViaVersion#678] opened 2017-06-04 22:28 UTC
Sometimes when a player died in void they're unable to respawn because respawn button is grayed out, even after rejoining respawn button is still grayed out, this is an issue on non-1.8 clients, if the same player rejoins with 1.8 client he would be able to click "respawn".

### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/f20150b33bdda048830680c1179b8f1f

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord, NuVotifier

### How does this error happen? login? Using an item? 
Somewhat random usually when a player died in void.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No.

**Comment by L4BORG** [comment] 2017-06-04 22:30
Also, we have this in spigot.yml:

```stats:
  disable-saving: false
  forced-stats:
    achievement:
      openInventory: 1```

as advised here: https://www.spigotmc.org/wiki/spigot-configuration/#stats

**Comment by MylesIsCool** [comment] 2017-06-05 14:37
I've attempted to replicate this issue with 1.11.2 on a 1.8 server by teleporting to the void and it causing me to die. I've tried this 40+ times and cannot replicate the issue above.

It would be appreciated if you could try without ProtocolLib / plugins using it and see if this changes anything, otherwise, if you were able to test with plugins disable it would be appreciated.

**Comment by L4BORG** [comment] 2017-06-05 19:23
We're using

```
>protocol version
[21:22:26 INFO]: ProtocolLib v3.6.5
[21:22:26 INFO]: Authors: dmulloy2 and Comphenix
[21:22:26 INFO]: Issues: https://github.com/dmulloy2/ProtocolLib/issues
```

```
>ncp version
[21:23:03 INFO]: ---- Version information ----
[21:23:03 INFO]: #### Server ####
[21:23:03 INFO]: git-TacoSpigot-"65fd35f" ~MC: 1.8.8~
[21:23:03 INFO]:   detected: 1.8.8
[21:23:03 INFO]: #### NoCheatPlus ####
[21:23:03 INFO]: Plugin: 3.15.2-SNAPSHOT-sMD5NET-b1113
[21:23:03 INFO]: MCAccess: 1.8.4-1.8.8 / Spigot-CB-1.8_R3
[21:23:03 INFO]: Features:
[21:23:03 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
[21:23:03 INFO]:   checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[21:23:03 INFO]:   defaults: pvpKnockBackVelocity
[21:23:03 INFO]:   packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | CatchAllAdapter
[21:23:03 INFO]: #### Related Plugins ####
[21:23:03 INFO]: ProtocolLib v3.6.5 | ViaVersion v1.0.5-SNAPSHOT
```

**Comment by MylesIsCool** [comment] 2017-06-24 13:46
Did you get any results from trying with different plugins? This is till something we've had nobody able to replicate.

**Comment by L4BORG** [comment] 2017-06-24 15:04
Kinda, I can't really test without ProtocolLib as we have too many plugins that depend on it. Which version of protocollib is recommended for ViaVersion on 1.8.8? We did try downgrading (from TacoSpigot to PaperSpigot) and we're kinda observing results, the problem is issue is somehwat random :|

**Comment by MylesIsCool** [comment] 2017-06-24 15:08
@L4BORG The latest that supports 1.8.8 I guess, I've never used a specific build

**Comment by Inuun** [comment] 2017-06-24 21:30
I think, this is not caused by ViaVersion. This is caused by Spigot/Minecraft bug. Sometimes on dead I can't click respawn button, experienced this without viaversion too.

**Comment by L4BORG** [comment] 2017-06-24 21:48
If so, why can the player only respawn with 1.8 client once he gets "bugged"?

**Comment by L4BORG** [comment] 2017-06-24 21:51
With spigot this could be caused if there's no 

```
  disable-saving: false
  forced-stats:
    achievement:
      openInventory: 1
```

in spigot.yml as I explained in previous comments. But now that I think about it, how does ViaVersion handle achievements?

**Comment by MylesIsCool** [comment] 2017-06-25 22:06
ViaVersion passes through achievements and does not modify them.

**Comment by MylesIsCool** [comment] 2017-08-22 23:11
I'm going to close this as really there's no info we have to replicate this constantly. If something comes up i'll be happy (if you can give a zip of a minimal server config with the issue)

**Closed by MylesIsCool** 2017-08-22 23:11 UTC
Labels: Can't Reproduce... Yet!
