### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Eternalrealms** [MylesIsCool/ViaVersion#242] opened 2016-03-17 22:30 UTC
### What version of ViaVersion are you using? Type /ver viaversion
0.6.4
### What version of Spigot are you using? Type /ver
Spigot 1.8.8
### What plugins are you using? Type /plugins
Protocal lib, essentials, viaver, nocheatplus, Bukkit-Connect
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
I used Lilypad (Its an alternative to Bungee), no plugins
### How does this error happen? login? Using an item? 
I noticed this when someone was logging in.
### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://hastebin.com/erewisanid.vbs

**Comment by HugoDaBosss** [comment] 2016-03-18 16:19
Duplicate of #149 #194 #202 and #243

**Comment by MylesIsCool** [comment] 2016-03-20 16:47
Use 0.6.7, closing issue. Request reopen if still occurs.

**Closed by MylesIsCool** 2016-03-20 16:47 UTC
Labels: Duplicate
