### ISSUE TITLE
Big lag on join

### ISSUE THREAD

**Issue by CT16** [MylesIsCool/ViaVersion#588] opened 2016-11-28 21:00 UTC
### What is the output link of /viaversion dump? 

http://hastebin.com/ocatotulus.json (I removed my plugin list because other than Buycraft and ViaVersion they're 100% custom)

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

BungeeCord. Custom plugins.

### How does this error happen? login? Using an item? 

On login. It lags on join for anywhere between 1 and 5 seconds. The servers themselves aren't lagging. Definitely a ViaVersion issue.

It DOESN'T lag in 1.8 client, just all other versions. (lag = teleporting players back after trying to move within this time, can't use hotbar etc but it doesn't lag right away, since the hotbar fills and the sidebar activates, it maybe at least 2 ticks in)

### Is there an error in the console? Use pastebin.com. Is there a kick message?

No

**Comment by MylesIsCool** [comment] 2016-11-28 22:19
The point of the dump is to provide useful information. Removing info does not help this, I don't think this is related to ViaVersion directly and could just be Minecraft.

**Comment by MylesIsCool** [comment] 2016-12-20 20:17
Closing as duplicate of other, if you want this solved, reply to the other one with more info.

**Closed by MylesIsCool** 2016-12-20 20:17 UTC
