### ISSUE TITLE
minecraft:spawn_egg => Null Ref => :-(

### ISSUE THREAD

**Issue by michaeljfarr** [MylesIsCool/ViaVersion#887] opened 2018-07-20 07:49 UTC
Users will not be able to login, or will immediately lose their connection if they hold a spawn_egg.  This only occurs for spawn egg without an attached entity type.  You can get this type of egg a few ways, but the most obvious is this: /give <player> minecraft:spawn_egg

### What is the output link of /viaversion dump? 
viaversion 1.4.0

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No, This happens with all other plugins removed.

### How does this error happen? login? Using an item? 
Use minecraft client 1.13, connect to viaversion 1.4 running spigot server 1.12.2
/give <player> minecraft:spawn_egg

### Is there an error in the console? Use pastebin.com. Is there a kick message?

An error occurred with entity metadata handler
Metadata: Metadata(id=6, metaType=Slot, value=Item(id=383, amount=1, data=0, tag=null))

https://pastebin.com/pxLdpLH3

**Comment by Matsv** [comment] 2018-07-20 08:20
Duplicate of #868, fixed in the latest devbuild (https://ci.viaversion.com/job/ViaVersion/).
Please provide your ViaVersion dump in the future (:

**Closed by Matsv** 2018-07-20 08:20 UTC
