### ISSUE TITLE
Wrong sounds

### ISSUE THREAD

**Issue by checkplys** [MylesIsCool/ViaVersion#53] opened 2016-03-02 22:06 UTC
When a 1.8 player closes a fence gate it makes a sound of a arrow sometimes.
and other times a random ghast sounds just appear, I don't know what is making the ghast song.

**Comment by checkplys** [comment] 2016-03-02 22:12
#10

**Comment by MylesIsCool** [comment] 2016-03-02 23:57
Closed, duplicate of #10

**Closed by MylesIsCool** 2016-03-02 23:57 UTC
