### ISSUE TITLE
Hologram Glitches

### ISSUE THREAD

**Issue by ChavitaHD** [MylesIsCool/ViaVersion#71] opened 2016-03-03 03:54 UTC
On 1.9 the holograms look to high: http://prntscr.com/aaj5tu
On 1.8 the holograms look normal: http://prntscr.com/aaj60v

**Comment by Paulomart** [comment] 2016-03-03 05:47
Duplicate of #20 please close

**Closed** 2016-03-03 05:49 UTC
