### ISSUE TITLE
It takes ages to switch servers on bungee

### ISSUE THREAD

**Issue by Paulomart** [MylesIsCool/ViaVersion#109] opened 2016-03-03 21:46 UTC
### What version of ViaVersion are you using? Type /ver viaversion
0.4.6
### What version of Spigot are you using? Type /ver
git-Spigot-e4d4710-e1ebe52
### What plugins are you using? /plugins
ViaVersion, PrococolLib + Custom
### How does this error happen? login? using an item? 
When switching servers
### Is there an error in the console? Use pastebin.com. Is there a kick message?

**Could this because Im sending spawn packets of NPCs + Holograms so eaily?**

```
[22:35:10 INFO]: UUID of player Paulomart is c4ee8311-4150-481b-849f-8a8a263421b0
[22:35:10 INFO]: Paulomart[/84.160.157.23:40725] logged in with entity id 57 at ([world]2070.5, 110.0, 433.5)
[22:35:10 INFO]: Unable to get entity for ID: 28
[22:35:10 INFO]: Unable to get entity for ID: 29
[22:35:10 INFO]: Unable to get entity for ID: 30
[22:35:10 INFO]: Unable to get entity for ID: 31
[22:35:10 INFO]: Unable to get entity for ID: 32
[22:35:10 INFO]: Unable to get entity for ID: 33
[22:35:10 INFO]: Unable to get entity for ID: 34
[22:35:10 INFO]: Unable to get entity for ID: 35
[22:35:10 INFO]: Unable to get entity for ID: 36
[22:35:10 INFO]: Unable to get entity for ID: 37
[22:35:10 INFO]: Unable to get entity for ID: 38
[22:35:10 INFO]: Unable to get entity for ID: 39
[22:35:10 INFO]: Unable to get entity for ID: 40
[22:35:10 INFO]: Unable to get entity for ID: 41
[22:35:11 INFO]: Unable to get entity for ID: 28
[22:35:11 INFO]: Unable to get entity for ID: 29
[22:35:11 INFO]: Unable to get entity for ID: 30
[22:35:11 INFO]: Unable to get entity for ID: 31
[22:35:11 INFO]: Unable to get entity for ID: 32
[22:35:11 INFO]: Unable to get entity for ID: 33
[22:35:11 INFO]: Unable to get entity for ID: 34
[22:35:11 INFO]: Unable to get entity for ID: 35
[22:35:11 INFO]: Unable to get entity for ID: 36
[22:35:11 INFO]: Unable to get entity for ID: 37
[22:35:11 INFO]: Unable to get entity for ID: 38
[22:35:11 INFO]: Unable to get entity for ID: 39
[22:35:11 INFO]: Unable to get entity for ID: 40
[22:35:11 INFO]: Unable to get entity for ID: 41
[22:35:11 INFO]: Unable to get entity for ID: 28
[22:35:11 INFO]: Unable to get entity for ID: 29
[22:35:11 INFO]: Unable to get entity for ID: 30
[22:35:11 INFO]: Unable to get entity for ID: 31
[22:35:11 INFO]: Unable to get entity for ID: 32
[22:35:11 INFO]: Unable to get entity for ID: 33
[22:35:11 INFO]: Unable to get entity for ID: 34
[22:35:11 INFO]: Unable to get entity for ID: 35
[22:35:11 INFO]: Unable to get entity for ID: 36
[22:35:11 INFO]: Unable to get entity for ID: 37
[22:35:11 INFO]: Unable to get entity for ID: 38
[22:35:11 INFO]: Unable to get entity for ID: 39
[22:35:11 INFO]: Unable to get entity for ID: 40
[22:35:11 INFO]: Unable to get entity for ID: 41
[22:35:12 INFO]: Unable to get entity for ID: 28
[22:35:12 INFO]: Unable to get entity for ID: 29
[22:35:12 INFO]: Unable to get entity for ID: 30
[22:35:12 INFO]: Unable to get entity for ID: 31
[22:35:12 INFO]: Unable to get entity for ID: 32
[22:35:12 INFO]: Unable to get entity for ID: 33
[22:35:12 INFO]: Unable to get entity for ID: 34
[22:35:12 INFO]: Unable to get entity for ID: 35
[22:35:12 INFO]: Unable to get entity for ID: 36
[22:35:12 INFO]: Unable to get entity for ID: 37
[22:35:12 INFO]: Unable to get entity for ID: 38
[22:35:12 INFO]: Unable to get entity for ID: 39
[22:35:12 INFO]: Unable to get entity for ID: 40
[22:35:12 INFO]: Unable to get entity for ID: 41
[22:35:12 INFO]: Unable to get entity for ID: 28
[22:35:12 INFO]: Unable to get entity for ID: 29
[22:35:12 INFO]: Unable to get entity for ID: 30
[22:35:12 INFO]: Unable to get entity for ID: 31
[22:35:12 INFO]: Unable to get entity for ID: 32
[22:35:12 INFO]: Unable to get entity for ID: 33
[22:35:12 INFO]: Unable to get entity for ID: 34
[22:35:12 INFO]: Unable to get entity for ID: 35
[22:35:12 INFO]: Unable to get entity for ID: 36
[22:35:12 INFO]: Unable to get entity for ID: 37
[22:35:12 INFO]: Unable to get entity for ID: 38
[22:35:12 INFO]: Unable to get entity for ID: 39
[22:35:12 INFO]: Unable to get entity for ID: 40
[22:35:12 INFO]: Unable to get entity for ID: 41
[22:35:13 INFO]: Unable to get entity for ID: 28
[22:35:13 INFO]: Unable to get entity for ID: 29
[22:35:13 INFO]: Unable to get entity for ID: 30
[22:35:13 INFO]: Unable to get entity for ID: 31
[22:35:13 INFO]: Unable to get entity for ID: 32
[22:35:13 INFO]: Unable to get entity for ID: 33
[22:35:13 INFO]: Unable to get entity for ID: 34
[22:35:13 INFO]: Unable to get entity for ID: 35
[22:35:13 INFO]: Unable to get entity for ID: 36
[22:35:13 INFO]: Unable to get entity for ID: 37
[22:35:13 INFO]: Unable to get entity for ID: 38
[22:35:13 INFO]: Unable to get entity for ID: 39
[22:35:13 INFO]: Unable to get entity for ID: 40
[22:35:13 INFO]: Unable to get entity for ID: 41
[22:35:13 INFO]: Unable to get entity for ID: 28
[22:35:13 INFO]: Unable to get entity for ID: 29
[22:35:13 INFO]: Unable to get entity for ID: 30
[22:35:13 INFO]: Unable to get entity for ID: 31
[22:35:13 INFO]: Unable to get entity for ID: 32
[22:35:13 INFO]: Unable to get entity for ID: 33
[22:35:13 INFO]: Unable to get entity for ID: 34
[22:35:13 INFO]: Unable to get entity for ID: 35
[22:35:13 INFO]: Unable to get entity for ID: 36
[22:35:13 INFO]: Unable to get entity for ID: 37
[22:35:13 INFO]: Unable to get entity for ID: 38
[22:35:13 INFO]: Unable to get entity for ID: 39
[22:35:13 INFO]: Unable to get entity for ID: 40
[22:35:13 INFO]: Unable to get entity for ID: 41
[22:35:14 INFO]: Unable to get entity for ID: 28
[22:35:14 INFO]: Unable to get entity for ID: 29
[22:35:14 INFO]: Unable to get entity for ID: 30
[22:35:14 INFO]: Unable to get entity for ID: 31
[22:35:14 INFO]: Unable to get entity for ID: 32
[22:35:14 INFO]: Unable to get entity for ID: 33
[22:35:14 INFO]: Unable to get entity for ID: 34
[22:35:14 INFO]: Unable to get entity for ID: 35
[22:35:14 INFO]: Unable to get entity for ID: 36
[22:35:14 INFO]: Unable to get entity for ID: 37
[22:35:14 INFO]: Unable to get entity for ID: 38
[22:35:14 INFO]: Unable to get entity for ID: 39
[22:35:14 INFO]: Unable to get entity for ID: 40
[22:35:14 INFO]: Unable to get entity for ID: 41
[22:35:14 INFO]: Unable to get entity for ID: 28
[22:35:14 INFO]: Unable to get entity for ID: 29
[22:35:14 INFO]: Unable to get entity for ID: 30
[22:35:14 INFO]: Unable to get entity for ID: 31
[22:35:14 INFO]: Unable to get entity for ID: 32
[22:35:14 INFO]: Unable to get entity for ID: 33
[22:35:14 INFO]: Unable to get entity for ID: 34
[22:35:14 INFO]: Unable to get entity for ID: 35
[22:35:14 INFO]: Unable to get entity for ID: 36
[22:35:14 INFO]: Unable to get entity for ID: 37
[22:35:14 INFO]: Unable to get entity for ID: 38
[22:35:14 INFO]: Unable to get entity for ID: 39
[22:35:14 INFO]: Unable to get entity for ID: 40
[22:35:14 INFO]: Unable to get entity for ID: 41
[22:35:15 INFO]: Unable to get entity for ID: 28
[22:35:15 INFO]: Unable to get entity for ID: 29
[22:35:15 INFO]: Unable to get entity for ID: 30
[22:35:15 INFO]: Unable to get entity for ID: 31
[22:35:15 INFO]: Unable to get entity for ID: 32
[22:35:15 INFO]: Unable to get entity for ID: 33
[22:35:15 INFO]: Unable to get entity for ID: 34
[22:35:15 INFO]: Unable to get entity for ID: 35
[22:35:15 INFO]: Unable to get entity for ID: 36
[22:35:15 INFO]: Unable to get entity for ID: 37
[22:35:15 INFO]: Unable to get entity for ID: 38
[22:35:15 INFO]: Unable to get entity for ID: 39
[22:35:15 INFO]: Unable to get entity for ID: 40
[22:35:15 INFO]: Unable to get entity for ID: 41
[22:35:15 INFO]: Unable to get entity for ID: 28
[22:35:15 INFO]: Unable to get entity for ID: 29
[22:35:15 INFO]: Unable to get entity for ID: 30
[22:35:15 INFO]: Unable to get entity for ID: 31
[22:35:15 INFO]: Unable to get entity for ID: 32
[22:35:15 INFO]: Unable to get entity for ID: 33
[22:35:15 INFO]: Unable to get entity for ID: 34
[22:35:15 INFO]: Unable to get entity for ID: 35
[22:35:15 INFO]: Unable to get entity for ID: 36
[22:35:15 INFO]: Unable to get entity for ID: 37
[22:35:15 INFO]: Unable to get entity for ID: 38
[22:35:15 INFO]: Unable to get entity for ID: 39
[22:35:15 INFO]: Unable to get entity for ID: 40
[22:35:15 INFO]: Unable to get entity for ID: 41
[22:35:16 INFO]: Unable to get entity for ID: 28
[22:35:16 INFO]: Unable to get entity for ID: 29
[22:35:16 INFO]: Unable to get entity for ID: 30
[22:35:16 INFO]: Unable to get entity for ID: 31
[22:35:16 INFO]: Unable to get entity for ID: 32
[22:35:16 INFO]: Unable to get entity for ID: 33
[22:35:16 INFO]: Unable to get entity for ID: 34
[22:35:16 INFO]: Unable to get entity for ID: 35
[22:35:16 INFO]: Unable to get entity for ID: 36
[22:35:16 INFO]: Unable to get entity for ID: 37
[22:35:16 INFO]: Unable to get entity for ID: 38
[22:35:16 INFO]: Unable to get entity for ID: 39
[22:35:16 INFO]: Unable to get entity for ID: 40
[22:35:16 INFO]: Unable to get entity for ID: 41
[22:35:16 INFO]: Unable to get entity for ID: 28
[22:35:16 INFO]: Unable to get entity for ID: 29
[22:35:16 INFO]: Unable to get entity for ID: 30
[22:35:16 INFO]: Unable to get entity for ID: 31
[22:35:16 INFO]: Unable to get entity for ID: 32
[22:35:16 INFO]: Unable to get entity for ID: 33
[22:35:16 INFO]: Unable to get entity for ID: 34
[22:35:16 INFO]: Unable to get entity for ID: 35
[22:35:16 INFO]: Unable to get entity for ID: 36
[22:35:16 INFO]: Unable to get entity for ID: 37
[22:35:16 INFO]: Unable to get entity for ID: 38
[22:35:16 INFO]: Unable to get entity for ID: 39
[22:35:16 INFO]: Unable to get entity for ID: 40
[22:35:16 INFO]: Unable to get entity for ID: 41
[22:35:17 INFO]: Unable to get entity for ID: 28
[22:35:17 INFO]: Unable to get entity for ID: 29
[22:35:17 INFO]: Unable to get entity for ID: 30
[22:35:17 INFO]: Unable to get entity for ID: 31
[22:35:17 INFO]: Unable to get entity for ID: 32
[22:35:17 INFO]: Unable to get entity for ID: 33
[22:35:17 INFO]: Unable to get entity for ID: 34
[22:35:17 INFO]: Unable to get entity for ID: 35
[22:35:17 INFO]: Unable to get entity for ID: 36
[22:35:17 INFO]: Unable to get entity for ID: 37
[22:35:17 INFO]: Unable to get entity for ID: 38
[22:35:17 INFO]: Unable to get entity for ID: 39
[22:35:17 INFO]: Unable to get entity for ID: 40
[22:35:17 INFO]: Unable to get entity for ID: 41
[22:35:17 INFO]: Unable to get entity for ID: 28
[22:35:17 INFO]: Unable to get entity for ID: 29
[22:35:17 INFO]: Unable to get entity for ID: 30
[22:35:17 INFO]: Unable to get entity for ID: 31
[22:35:17 INFO]: Unable to get entity for ID: 32
[22:35:17 INFO]: Unable to get entity for ID: 33
[22:35:17 INFO]: Unable to get entity for ID: 34
[22:35:17 INFO]: Unable to get entity for ID: 35
[22:35:17 INFO]: Unable to get entity for ID: 36
[22:35:17 INFO]: Unable to get entity for ID: 37
[22:35:17 INFO]: Unable to get entity for ID: 38
[22:35:17 INFO]: Unable to get entity for ID: 39
[22:35:17 INFO]: Unable to get entity for ID: 40
[22:35:17 INFO]: Unable to get entity for ID: 41
[22:35:18 INFO]: Unable to get entity for ID: 28
[22:35:18 INFO]: Unable to get entity for ID: 29
[22:35:18 INFO]: Unable to get entity for ID: 30
[22:35:18 INFO]: Unable to get entity for ID: 31
[22:35:18 INFO]: Unable to get entity for ID: 32
[22:35:18 INFO]: Unable to get entity for ID: 33
[22:35:18 INFO]: Unable to get entity for ID: 34
[22:35:18 INFO]: Unable to get entity for ID: 35
[22:35:18 INFO]: Unable to get entity for ID: 36
[22:35:18 INFO]: Unable to get entity for ID: 37
[22:35:18 INFO]: Unable to get entity for ID: 38
[22:35:18 INFO]: Unable to get entity for ID: 39
[22:35:18 INFO]: Unable to get entity for ID: 40
[22:35:18 INFO]: Unable to get entity for ID: 41
[22:35:18 INFO]: Unable to get entity for ID: 28
[22:35:18 INFO]: Unable to get entity for ID: 29
[22:35:18 INFO]: Unable to get entity for ID: 30
[22:35:18 INFO]: Unable to get entity for ID: 31
[22:35:18 INFO]: Unable to get entity for ID: 32
[22:35:18 INFO]: Unable to get entity for ID: 33
[22:35:18 INFO]: Unable to get entity for ID: 34
[22:35:18 INFO]: Unable to get entity for ID: 35
[22:35:18 INFO]: Unable to get entity for ID: 36
[22:35:18 INFO]: Unable to get entity for ID: 37
[22:35:18 INFO]: Unable to get entity for ID: 38
[22:35:18 INFO]: Unable to get entity for ID: 39
[22:35:18 INFO]: Unable to get entity for ID: 40
[22:35:18 INFO]: Unable to get entity for ID: 41
[22:35:19 INFO]: Unable to get entity for ID: 28
[22:35:19 INFO]: Unable to get entity for ID: 29
[22:35:19 INFO]: Unable to get entity for ID: 30
[22:35:19 INFO]: Unable to get entity for ID: 31
[22:35:19 INFO]: Unable to get entity for ID: 32
[22:35:19 INFO]: Unable to get entity for ID: 33
[22:35:19 INFO]: Unable to get entity for ID: 34
[22:35:19 INFO]: Unable to get entity for ID: 35
[22:35:19 INFO]: Unable to get entity for ID: 36
[22:35:19 INFO]: Unable to get entity for ID: 37
[22:35:19 INFO]: Unable to get entity for ID: 38
[22:35:19 INFO]: Unable to get entity for ID: 39
[22:35:19 INFO]: Unable to get entity for ID: 40
[22:35:19 INFO]: Unable to get entity for ID: 41
[22:35:19 INFO]: Unable to get entity for ID: 28
[22:35:19 INFO]: Unable to get entity for ID: 29
[22:35:19 INFO]: Unable to get entity for ID: 30
[22:35:19 INFO]: Unable to get entity for ID: 31
[22:35:19 INFO]: Unable to get entity for ID: 32
[22:35:19 INFO]: Unable to get entity for ID: 33
[22:35:19 INFO]: Unable to get entity for ID: 34
[22:35:19 INFO]: Unable to get entity for ID: 35
[22:35:19 INFO]: Unable to get entity for ID: 36
[22:35:19 INFO]: Unable to get entity for ID: 37
[22:35:19 INFO]: Unable to get entity for ID: 38
[22:35:19 INFO]: Unable to get entity for ID: 39
[22:35:19 INFO]: Unable to get entity for ID: 40
[22:35:19 INFO]: Unable to get entity for ID: 41
[22:35:20 INFO]: Unable to get entity for ID: 28
[22:35:20 INFO]: Unable to get entity for ID: 29
[22:35:20 INFO]: Unable to get entity for ID: 30
[22:35:20 INFO]: Unable to get entity for ID: 31
[22:35:20 INFO]: Unable to get entity for ID: 32
[22:35:20 INFO]: Unable to get entity for ID: 33
[22:35:20 INFO]: Unable to get entity for ID: 34
[22:35:20 INFO]: Unable to get entity for ID: 35
[22:35:20 INFO]: Unable to get entity for ID: 36
[22:35:20 INFO]: Unable to get entity for ID: 37
[22:35:20 INFO]: Unable to get entity for ID: 38
[22:35:20 INFO]: Unable to get entity for ID: 39
[22:35:20 INFO]: Unable to get entity for ID: 40
[22:35:20 INFO]: Unable to get entity for ID: 41
```

**Comment by themanwithaplan2** [comment] 2016-03-04 01:20
I have the same issue where it takes a good 10 seconds to join another server on my bungeecord if I'm on 1.9, however I do not have these console errors and if I use a 1.8 client the issue is not present

**Comment by Paulomart** [comment] 2016-03-04 05:56
Likely because you don't spawn Entities with packets

**Comment by Paulomart** [comment] 2016-03-04 05:56
It must be another cause then

**Comment by HugoDaBosss** [comment] 2016-03-04 12:03
In 1.9 it takes significantly longer to load a new world, even in singeplayer. This may be the cause of your issue.

**Comment by Paulomart** [comment] 2016-03-04 13:36
But so long, I will add a 1.9 server to my network and test that

**Comment by HugoDaBosss** [comment] 2016-03-27 13:12
So what's the state of this?
I'm not experiencing this anymore with the latest versions and 1.9 client.

**Comment by Paulomart** [comment] 2016-03-27 13:45
I'm currently on holiday and have no way to test this. I will look into when I'm back

**Comment by MylesIsCool** [comment] 2016-03-30 15:45
Closing cannot replicate on 0.7.0, using BungeeCord takes less than a second to switch on a network using Protocol Lib, Via, and other plugins.

**Closed by MylesIsCool** 2016-03-30 15:45 UTC
