### ISSUE TITLE
1.11 Roadmap

### ISSUE THREAD

**Issue by Matsv** [MylesIsCool/ViaVersion#482] opened 2016-08-10 15:15 UTC
## Please report any issues you have with the 1.11 build in the comments.

You might have noticed that there is a '[1.11-DEV' branch](https://github.com/MylesIsCool/ViaVersion/tree/1.11-DEV). We are following the development of 1.11 to be compatible with it when it gets released. 

**Please know that this builds might be unstable and are not meant for production use.**

_We'll only support the latest snapshot, when a new one comes out, previous one will get dropped, please test it on the latest version before you report issues_

**Current compatible snapshot:** 1.11-pre1
**Downloads**: [BuildServer](https://ci.viaversion.com/job/ViaVersion_1.11-DEV/)

**TODO:**
- [x] Handle title packet changes

**Comment by MylesIsCool** [comment] 2016-08-10 15:21
Currently the release seems to be playable, things like Zombie Villagers don't appear to be showing up as Villagers but Zombies (due to entity id changes).

**Comment by MylesIsCool** [comment] 2016-08-10 17:05
As an update, we've finished documenting the changes to Metadata (me & Mats):

http://wiki.vg/Pre-release_protocol

**Comment by TiTo-418** [comment] 2016-08-20 05:22
Hey, 1.11 clients can't join the server, these are the logs http://pastebin.com/SV85Hyes
And this is the kick msg http://prntscr.com/c80u2y

**Comment by Lmmb74** [comment] 2016-08-20 05:37
Hey man, that is sportbukkit. So it might be caused by that.

**Comment by Matsv** [comment] 2016-08-20 08:08
@TiTo-418 I can't reproduce the issue. Please try to debug it, remove some plugins and try to use normal Spigot.

**Comment by TheIntelloBox** [comment] 2016-08-26 17:52
Hello,

When I download the alpha-version (with 1.11), I can't join the server with 1.11 (the latest snapshot) because there are too many packets. Try to see with NoCheatPlus, I think it's the problem.

**Comment by Matsv** [comment] 2016-08-26 17:53
@TheIntelloBox could you give us the link of /viaver dump and tell us the exact message when you get kicked?

**Comment by TheIntelloBox** [comment] 2016-08-27 07:48
http://hastebin.com/pinosepone.cpp
Error : internal exception io.netty.handler.codec.decoderexception java.io.exception:Packet69 (id) was larger than I excepted, found 11 bytes extra whilst reading packet 69

**Comment by Matsv** [comment] 2016-08-27 08:05
@TheIntelloBox On what versions does this happen?

**Comment by TheIntelloBox** [comment] 2016-08-27 08:21
I don't want that all my players see my plugins so I edited the list.

This happens on the latest snapshot : 16w33a. :)

**Comment by Matsv** [comment] 2016-08-27 08:23
Could you send your full dump privately to me in that case? https://gitter.im/Matsv 
We can't help you without the full list.

**Comment by InfinityAspire** [comment] 2016-09-27 03:06
Using newest build of 1.11 Dev on newest 1.10.2 build of Spigot with Builder 1189 of Bungee. 1.11 clients are simply shown 'Outdated Server' when trying to connect

**Comment by Matsv** [comment] 2016-09-27 06:57
@InfinityAspire Bungeecord never supports snapshots until the full version is released. There might be forks that follow the development.

**Comment by Matsv** [comment] 2016-09-30 18:14
Please note that the Hologram patch isn't currently in the 1.11 branch. We are working on modules to make ViaVersion compatible with multiple platforms. This change will be implemented for the 1.11 release or earlier depending on the state of it.

Smaller changes will still be pushed to the 1.11 branch.
If you can't wait for it or want more information: #505

**Comment by Matsv** [comment] 2016-10-02 11:30
@InfinityAspire We are working on a Bungee version of ViaVersion. It currently also supports 1.11 and works on Bungee side, so it doesn't have to be installed on your Spigot server. #505 for more information.

**Comment by InfinityAspire** [comment] 2016-10-02 14:01
Tried that build, all of my clients couldn't connect with the message 'Outdated Client, Please use 1.10.2'

**Comment by MylesIsCool** [comment] 2016-10-02 16:08
@InfinityAspire This is with connecting with the latest snapshot? on modular

**Comment by Matsv** [comment] 2016-10-04 17:41
Sounds should work correctly now.

**Comment by InfinityAspire** [comment] 2016-10-05 08:35
@MylesIsCool It was the latest snapshot, seems to be fixed now. @Matsv Will there be a Bungee version of ViaBackwards and with the Modules version of ViaVersion, I can remove it from my Bukkit instances right?

**Comment by Matsv** [comment] 2016-10-05 11:35
@InfinityAspire the goal is to also have a ViaBackwards for bungee, yes. It's currently not, though. There seems to be some chunk issues that only occurs on bungee, didn't have the time yet to really look into it.

**Comment by Matsv** [comment] 2016-11-14 15:21
The 1.11 update is released.

**Closed** 2016-11-14 15:20 UTC
Labels: Help Wanted
