### ISSUE TITLE
NullPointerException on Sponge 1.12.1

### ISSUE THREAD

**Issue by BrainStone** [MylesIsCool/ViaVersion#743] opened 2017-09-03 22:00 UTC
### How this error happens

When the plugin loads I get a NPE.

### Versions

```
Minecraft: 1.12.1
SpongeAPI: 7.0.0-SNAPSHOT-f06e7ff6
SpongeVanilla: 1.12.1-7.0.0-BETA-321
ViaVersion: 1.2.1-SNAPSHOT
```

### Error message

https://hastebin.com/mujoxawuzo.log

**Comment by MylesIsCool** [comment] 2017-09-09 15:37
I'm working on replicating your issue and have used the same sponge vanilla version and the latest dev build of ViaVersion.

I'm unable to replicate this, is it possible you can guide me from an empty folder on how to replicate this? (I've also tried a few later builds and 1.10.2 which someone else had the issue on and no luck)

**Comment by gaelitoelquesito** [comment] 2017-09-09 21:05
Hi! I'm having the same error. It's a clean server of Sponge. I tried to delete the viaversion config but it's still happening.

Error: http://prntscr.com/gj6kiz
SpongeVanilla: 1.12.1-7.0.0-BETA-321
ViaVersion: ViaVersion-1.2.1-SNAPSHOT (Latest build)

**Comment by MylesIsCool** [comment] 2017-09-09 21:08
@gaelitoelquesito Can you provide more info as obviously i've tried this and can't replicate?

**Comment by gaelitoelquesito** [comment] 2017-09-09 22:22
I've uploaded my server. https://mega.nz/#!Z4RWnZha!yfB12mTdaek_NGVuanPI_rXGY2LsRboUxkXGJ8RPSJg

**Comment by MylesIsCool** [comment] 2017-09-09 22:39
From initial testing seems to only happen when AsyncWorldEdit is loaded, works fine without for me.  Will look into more soon, but looks like an odd issue.

**Comment by gaelitoelquesito** [comment] 2017-09-09 22:43
Confirmed. Without FAWE it works well.

**Comment by phit** [comment] 2017-09-11 11:18
this is because this line

https://github.com/MylesIsCool/ViaVersion/blob/a64c21da8bd0aed181686116aa46c263b0a72fa6/common/src/main/java/us/myles/ViaVersion/util/Config.java#L39
it will take the first config.yml it can find, a bunch of other plugins besides FAWE can cause this aswell..

I ran into this a few months ago on 1.10.2 ![](https://i.imgur.com/YOFfLgM.png)

**Comment by MylesIsCool** [comment] 2017-09-11 12:12
This has been fixed in https://github.com/MylesIsCool/ViaVersion/commit/298835be42ee1811cee956d48db178bb221d8705, implemented using Assets API for Sponge. Credits of course to @phit for identifying the cause as well as info on how to solve it. :)

**Closed by MylesIsCool** 2017-09-11 12:12 UTC
Labels: Need more info, Sponge Version
