### ISSUE TITLE
Crashes with pistons (1.11 client on 1.10.2 server)

### ISSUE THREAD

**Issue by Black-Hole** [MylesIsCool/ViaVersion#570] opened 2016-11-18 19:06 UTC
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
1.11 client connecting to ViaVersion 1.0.1 running on BungeeCord 1.11. Minecraft servers are at 1.10.2, no plugin that manipulates packets.

### How does this error happen? login? Using an item? 
Retract some piston constructions at certain locations.
To reproduce use worldedit to load and paste http://www.mediafire.com/file/bjedvdc9t5d8w5a/pistoncrasher.schematic at -456 100 10. Then use the lever to extend and retract the pistons.

(This also happens while pistons extend and push 3 block high reeds at those locations.)

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Client crash log:
http://pastebin.com/HaWPCWF0

**Comment by Matsv** [comment] 2016-11-19 22:05
I'll try to reproduce it tomorrow.

**Comment by mcarey10** [comment] 2016-11-23 03:33
Experiencing same issue

**Comment by zedwick** [comment] 2016-11-25 15:00
This looks like the same issue, 1.11 clients crash connected to 1.8.8 server via bungeecord w/ viaversion 1.0.1

We were playing a modified version of SethBling/Cubehamster's Missile Wars (lots of pistons, seems very likely to experience a crash during a game. We had a crash 2/2 games)

https://pste.me/#/AngeW
https://pste.me/#/truKx
https://pste.me/#/crash-1-kiz
https://pste.me/#/crash-2-kiz
https://pste.me/#/kizs-is-smelly-mems-second-crash

**Comment by PhanaticD** [comment] 2016-12-11 11:46
bump same issue

**Comment by MylesIsCool** [comment] 2016-12-11 17:11
As an update to this issue as I finally got a bit of free time today (which sadly I won't have much more free time for a week for so).

It's caused by Minecraft updating the piston to air then triggering the block action packet to extend the piston.

It seems the behaviour for pistons has changed slightly in 1.11 in relation to lots of pistons being pushed causes air updates which leads to this issue.

This is not in vanilla but how easy it is to properly fix is hard to say, i've tried a few solutions of forcing the piston block to be set and it seems not to fix it. 

The only current workaround I have is disabling the push animation for pistons, which does work just not as satisfying. I'd be interested to know if you want this patch pushed or if you'd rather wait until we figure out the full fix. (The patch would only touch 1.11 clients)

**Comment by PhanaticD** [comment] 2016-12-11 19:30
anythings better than crashing

**Comment by Pokechu22** [comment] 2017-03-14 20:24
Pastebin link is dead, but if a new link is provided I can look at what's happening clientside, so if someone can repost it (possibly directly in the issue surrounded by <code>```</code> on both sides), that'd be helpful.

**Comment by MylesIsCool** [comment] 2017-03-15 16:33
@Pokechu22 I believe https://github.com/MylesIsCool/ViaVersion/issues/595 has it

**Comment by Pokechu22** [comment] 2017-03-15 16:44
Ah, good.  That's the crash that I expected (even hoped) to see; it's a vanilla issue (not exclusive to ViaVersion): [MC-110399](https://bugs.mojang.com/browse/MC-110339 "[MC-110399] Hopper: java.lang.IllegalArgumentException: Cannot get property atw{name=facing, clazz=class cv, values=[down, up, north, south, west, east]} as it does not exist in atk{block=minecraft:<block>, properties=[]}").  It was fixed in shapshot 16w50a (and thus 1.11.2), so all that needs to be done is to figure out how it was fixed there.  I'll do that in a bit; I don't have full access to my data right now (should have access in a few hours, though).

**Comment by Pokechu22** [comment] 2017-03-16 15:34
OK, I did some research, and that issue doesn't have as much info about it as I thought.  There _was_ a new block-36 NBT tag added in 1.11.2, but that doesn't seem related (given that 36's tile entity usually isn't ever sent).

However, I did identify some other changes in 1.11 to 1.11.2: the [block action](http://wiki.vg/Block_Actions#Piston) handler for the piston base switched from setting blocks with mode **2** (used in 1.11 and below, including 1.10.2) to using mode **3** in 1.11.2.  This happens when setting it to an extended piston base (from a retracted one), due to successful extension.  Note that block actions do occur server side, not just clientside.  Quoting from MCP:

> Sets the block state at a given location. Flag 1 will cause a block update. Flag 2 will send the change to
> clients (you almost always want this). Flag 4 prevents the block from being re-rendered, if this is a client
> world. Flags can be added together.

I don't _think_ that would directly effect it, but it's a line of investigation.

I also see that during piston movement, 1.11 uses `setBlockToAir` (which is equivilient to using mode 3).  1.11.2 uses a more complete set to air with mode 4 instead.  My guess is that those sets-to-air were received after the block action gets to the client, meaning the 36 block entity gets destroyed.  Maybe.  I'll need to test further.

There's a few other changes; I haven't digested them yet.

**Comment by Pokechu22** [comment] 2017-03-25 22:18
OK, still no clue as to what originally caused this; however, I will say that the workaround should probably only be enabled for 1.11.0, and disabled for 1.11.2; since that bug was supposedly fixed in 1.11.2, it shouldn't be needed there.

**Comment by MylesIsCool** [comment] 2017-06-24 13:49
With the above workaround provided going to close this issue unless something comes up in the future.

**Closed by MylesIsCool** 2017-06-24 13:49 UTC
Labels: Bug, Help Wanted, Workaround Provided
