### ISSUE TITLE
Cannot display item with zero amount

### ISSUE THREAD

**Issue by jiongjionger** [MylesIsCool/ViaVersion#575] opened 2016-11-21 09:40 UTC
### What is the output link of /viaversion dump? 
counld not paste dump(503 error)

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Nothing

### How does this error happen? login? Using an item? 
Some GUI use zero amount item to display deny menu. 1.11 client with ViaVersion(PaperSpigot 1.10.2). Zero amount items are not displayed.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
no

**Comment by Matsv** [comment] 2016-11-21 09:43
Duplicate of #553.

**Closed by Matsv** 2016-11-21 09:43 UTC
