### ISSUE TITLE
1.11 Players get crashed when stone is pushed by a piston

### ISSUE THREAD

**Issue by NinjaSlatz** [MylesIsCool/ViaVersion#595] opened 2016-12-04 21:57 UTC
### What is the output link of /viaversion dump? 
http://hastebin.com/onivedareg.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No, running Spigot 1.10.2

### How does this error happen? login? Using an item? 
When stone is being pushed by a piston, players in 1.10.2 and lower are fine, but players in 1.11 get their minecraft crashed with this message:

> java.lang.IllegalArgumentException: Cannot get property atw{name=facing, clazz=class cv, values=[down, up, north, south, west, east]} as it does not exist in atk{block=minecraft:air, properties=[]}
	at atk$a.c(SourceFile:166)
	at atd.j(SourceFile:119)
	at atd.f(SourceFile:130)
	at atd.F_(SourceFile:308)
	at ajq.k(SourceFile:1484)
	at beq.t(SourceFile:1649)
	at beq.av(SourceFile:967)
	at beq.a(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:124)
-- Head --
Thread: Client thread
Stacktrace:
	at atk$a.c(SourceFile:166)
	at atd.j(SourceFile:119)
	at atd.f(SourceFile:130)
	at atd.F_(SourceFile:308)
-- Block entity being ticked --
Details:
	Name: minecraft:piston // atd
	Block type: ID #36 (tile.null // atc)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-1175,129,583), Chunk: (at 9,8,7 in -74,36; contains blocks -1184,0,576 to -1169,255,591), Region: (-3,1; contains chunks -96,32 to -65,63, blocks -1536,0,512 to -1025,255,1023)
	Actual block type: ID #36 (tile.null // atc)
	Actual block data value: 4 / 0x4 / 0b0100
Stacktrace:
	at ajq.k(SourceFile:1484)

### Is there an error in the console? Use pastebin.com. Is there a kick message?
There is no error in the console.

**Comment by Matsv** [comment] 2016-12-04 22:27
Duplicate of #570

**Closed by Matsv** 2016-12-04 22:27 UTC
