### ISSUE TITLE
Exception showing up frequently in the log

### ISSUE THREAD

**Issue by teaearlgraycold** [MylesIsCool/ViaVersion#61] opened 2016-03-02 22:53 UTC
```
17:52:09 INFO]: ---------[/---.---.---.---:51682] logged in with entity id 8 at ([lobby]0.5, 99.0, -3.5)
[17:52:09 INFO]: An error occurred with entity meta data for PLAYER
[17:52:09 INFO]: Old ID: 1 New ID: 1
[17:52:09 INFO]: Old Type: Short New Type: VarInt
[17:52:09 WARN]: java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.Short
[17:52:09 WARN]:        at us.myles.ViaVersion.metadata.MetadataRewriter.writeMetadata1_9(MetadataRewriter.java:76)
[17:52:09 WARN]:        at us.myles.ViaVersion.transformers.OutgoingTransformer.transformMetadata(OutgoingTransformer.java:498)
[17:52:09 WARN]:        at us.myles.ViaVersion.transformers.OutgoingTransformer.transform(OutgoingTransformer.java:396)
[17:52:09 WARN]:        at us.myles.ViaVersion.handlers.ViaEncodeHandler.encode(ViaEncodeHandler.java:63)
[17:52:09 WARN]:        at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
[17:52:09 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:52:09 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[17:52:09 WARN]:        at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[17:52:09 WARN]:        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.encode(NettyChannelInjector.java:506)
[17:52:09 WARN]:        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$3.encode(NettyChannelInjector.java:264)
[17:52:09 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[17:52:09 WARN]:        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$3.write(NettyChannelInjector.java:270)
[17:52:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[17:52:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[17:52:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[17:52:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[17:52:09 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[17:52:09 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[17:52:09 WARN]:        at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:327)
[17:52:09 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[17:52:09 WARN]:        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6$3.run(NettyChannelInjector.java:361)
[17:52:09 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[17:52:09 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
[17:52:09 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[17:52:09 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

**Comment by Paulomart** [comment] 2016-03-02 22:54
Duplicate of #58 please close

**Comment by teaearlgraycold** [comment] 2016-03-02 22:57
Sorry, didn't look hard enough I guess.

**Closed** 2016-03-02 22:57 UTC
