### ISSUE TITLE
InvocationTargetException Console Spam

### ISSUE THREAD

**Issue by acasher** [MylesIsCool/ViaVersion#255] opened 2016-03-20 01:04 UTC
### What version of ViaVersion are you using? Type /ver viaversion
"Enabling ViaVersion v0.6.4"

### What version of Spigot are you using? Type /ver
git-Spigot-06ad352-4a7472d (MC: 1.8.8)

### What plugins are you using? Type /plugins
N/A

### Are you using any additional software like BungeeCord? If so, what software and version? 
"Enabled BungeeCord version git:BungeeCord-Bootstrap:1.9-SNAPSHOT:7926230:1123"

### How does this error happen? login? Using an item? 
Unknown. Been using ViaVersion for 2 weeks now and this is the first time it happened. The server was running fine for many hours and then these errors spammed the console to such a degree that the server logs reached 430 MB in size.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/raw/P3TDF3bx

**Comment by HugoDaBosss** [comment] 2016-03-20 11:11
Duplicate of #149 #194 #202 #242 and #243

**Comment by MylesIsCool** [comment] 2016-03-20 13:41
Could you use version 0.6.6?

Thanks.

**Comment by MylesIsCool** [comment] 2016-03-20 16:48
Use 0.6.7, closing issue. Request reopen if still occurs.

**Closed by MylesIsCool** 2016-03-20 16:48 UTC
Labels: Duplicate
