### ISSUE TITLE
EnderDragon skull

### ISSUE THREAD

**Issue by checkplys** [MylesIsCool/ViaVersion#51] opened 2016-03-02 22:05 UTC
When a 1.9 player places a enderdragon skull, 1.8 players see it as a skeleton skull

**Comment by gigosaurus** [comment] 2016-03-02 22:10
The enderdragon skull doesn't exist in 1.8. What are you expecting them to see?

**Comment by checkplys** [comment] 2016-03-02 22:11
The plugin can block 1.9 players of placing it, like with happens with 1.8->1.7 protocol hack, when a player try to use a 1.8 block, it just disappear

**Comment by Paulomart** [comment] 2016-03-02 22:22
It's because they just changed the data value. The server ignores this. Would say this is a wont fix.

**Comment by alexvermaning0** [comment] 2016-03-02 22:28
it works for me using the version 4.3

**Comment by Paulomart** [comment] 2016-03-02 22:28
It _cannot_ work

**Comment by alexvermaning0** [comment] 2016-03-02 22:28
and redstoneing works also

**Comment by alexvermaning0** [comment] 2016-03-02 22:29
what is your username
ill add you to the server 
ip: play.kwarkkings.us.to

**Comment by Paulomart** [comment] 2016-03-02 22:32
I'm on mobile. It's impossible to place the skull if you have a 1.8 server with ViaVersion. Maybe you are using 1.9 or something. I could also your client bugging but this is very unlikely.

**Comment by alexvermaning0** [comment] 2016-03-02 22:33
no if u want to join u can if u get on pc becuse it works using spigot 1.8.8 54 versions behind

**Comment by alexvermaning0** [comment] 2016-03-02 22:33
![2016-03-02_23 33 40](https://cloud.githubusercontent.com/assets/17603899/13478001/32731b84-e0cf-11e5-95d6-f17b55a6dfcb.png)

**Comment by alexvermaning0** [comment] 2016-03-02 22:38
there are 2 players online and no issue almost nothing is aproblem all the things in here are no problem with my version

**Comment by alexvermaning0** [comment] 2016-03-02 22:38
every bug is not a bug in this server exept from the boats

**Comment by Paulomart** [comment] 2016-03-02 22:41
Screen with /ver output please

**Comment by alexvermaning0** [comment] 2016-03-02 22:42
every1 can join my server and see almost bugfree server whitelist is off IP: play.kwarkkings.us.to

**Comment by Paulomart** [comment] 2016-03-02 22:45
Please stop advertising your server. All the people around here have either their own server or are not interested in joining yours. It just annoys people.

**Comment by Wilco2998** [comment] 2016-03-02 22:50
it's not for advertisments, it's just for proof.

**Comment by alexvermaning0** [comment] 2016-03-02 22:50
i dont want to adventising the server but its so people can see we don't have problems

**Comment by alexvermaning0** [comment] 2016-03-02 22:53
here is /ver it says craftbukkit but i got it from spigot 
![blabla](https://cloud.githubusercontent.com/assets/17603899/13478585/f6419142-e0d1-11e5-9095-2741c92b4c03.JPG)

**Comment by Paulomart** [comment] 2016-03-02 22:53
I see that but it would still be better if you seed a screenshot with the /ver output.

**Comment by alexvermaning0** [comment] 2016-03-02 22:55
it says than This server is not running any plugins by that name. use /plugins to get a list of plugins

**Comment by Paulomart** [comment] 2016-03-02 22:57
Sorry I didn't saw you last message. The server is then accepting invalid data from the client. You should update spigot too.

**Comment by alexvermaning0** [comment] 2016-03-02 22:57
yea but in this version almost no errors

**Comment by ridalarry** [comment] 2016-03-03 02:21
Instead of showing a skeleton skull maybe replacing it with the player "KingEndermen" head as it was the way to use dragon heads for dragon and its also used in the plugin PlayerHeads

**Comment by Paulomart** [comment] 2016-03-03 05:51
Just update your server. @MylesIsCool is this a won't fix?

**Comment by HugoDaBosss** [comment] 2016-03-03 08:48
I think if you want 1.9 functionality this plugin is not for you. If a player 1.9 player has a dragonhead the other players will be able to get a playerskull, which may be not appreciated by some server owners.

**Comment by Paulomart** [comment] 2016-03-03 11:38
But this is only caused because the server accepts the invalid data. Would like to see if this works on latest spigot

**Comment by MylesIsCool** [comment] 2016-03-03 15:45
Won't fix for now, does not break gameplay. May be visible in 1.9 but does not give any sort of advantage like other issues.

**Closed by MylesIsCool** 2016-03-03 15:45 UTC
