### ISSUE TITLE
Main Hand is in left instead of right

### ISSUE THREAD

**Issue by MrDarkness462** [MylesIsCool/ViaVersion#906] opened 2018-07-21 13:12 UTC
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/e7ec5684ff728eab186e25032c5d003ae9d9248c2dbc7c2b41b0f6ab0d8f71ff

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
i'm using BungeeCord with ViaVersion, ViaRewind, ViaBackwards in it

### How does this error happen? login? Using an item? 
When i'm on another server and i use /hub
it teleports me to the lobby with the main hand in the left
Lobby server it's on 1.12.2 and The other server that i connect it's on 1.8 with ViaVersion

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No errors

**Comment by dextonanderson** [comment] 2018-07-21 14:13
This sounds like you have your "Main Hand" setting changed to Left in the "Skin Customization" portion of the Minecraft settings.

![settings](https://i.imgur.com/LbelXZU.png)

**Comment by Matsv** [comment] 2018-07-22 01:34
Does this happen when you only instal ViaVersion/Backwards/Rewind on your spigot servers and not bungee?

**Comment by MrDarkness462** [comment] 2018-07-23 10:40
i have selected Main Right hand
But
When i use
ViaVersion/ViaRewind/ViaBackwards
on 1.12
and joining a server that it's linked with my bungeecord
with 1.8 this bugs occurs when i go back on the 1.12 server

But if i join a server that it's linked with my bungeecord too
with 1.12 this bugs doesn't exist anymore

**Comment by LoXR** [comment] 2018-07-27 02:31
Having this problem aswell.

**Comment by codingJWilliams** [comment] 2018-07-29 19:20
Duplicate of #798

**Closed** 2018-08-03 17:49 UTC
