### ISSUE TITLE
Invalid item in chat with item2chat

### ISSUE THREAD

**Issue by EnderGriefeur99** [MylesIsCool/ViaVersion#826] opened 2018-04-26 16:01 UTC
Invalid item in chat with item2chat please help me
<a href="https://imgur.com/VVNUF1k"><img src="https://i.imgur.com/VVNUF1k.png" title="source: imgur.com" /></a>

**Comment by Matsv** [comment] 2018-06-07 22:57
Duplicate of #779

**Closed by Matsv** 2018-06-07 22:57 UTC
