### ISSUE TITLE
Chunks don't render properly

### ISSUE THREAD

**Issue by SanderGielisse** [MylesIsCool/ViaVersion#38] opened 2016-03-02 15:30 UTC
Chunks don't render properly. The blocks are there but are displayed as some kind of "barrier block" to the client. Image: https://i.gyazo.com/45294748ae21d8b4afff92f5fdbb9cf7.png

**Comment by MylesIsCool** [comment] 2016-03-02 15:38
I'm assuming if you interact with them they load?

**Comment by tssge** [comment] 2016-03-02 16:06
I can confirm that if you break a block, they load.

**Comment by HugoDaBosss** [comment] 2016-03-02 16:50
Nice to see some Dutch people around here ;) But what kind of blocks are invisible? Is it just one type, or random ones. And by the way, isn't this a client-side issue?

**Comment by tssge** [comment] 2016-03-02 16:54
It seems to be random ones. For me it was stone, wood and brick.

**Comment by Paulomart** [comment] 2016-03-02 16:57
We had that in g++ too. Not sure how to fix this.

**Comment by Paulomart** [comment] 2016-03-02 17:00
Ref: GlowstoneMC/GlowstonePlusPlus#202

**Comment by SanderGielisse** [comment] 2016-03-02 17:06
Had this same problem with Enderstone, appeared that certain sent chunk packets were corrupted which had this as a result (not sure if this has the same cause). It fixes itself (unfortunately for only one session) when breaking a block in an invisible chunk.

**Comment by TrinityThiemo** [comment] 2016-03-02 17:28
Still broken for me, even breaking block will not fix it, it loads for a few seconds, and becomes trippy again

**Comment by wow4201** [comment] 2016-03-03 20:30
Also experiencing, oddly a naturally generated world doesn't have this problem, If I place a block, it loads the chunk. but if I login and out, it appears corrupted.

**Comment by xkuyax** [comment] 2016-03-03 20:52
On our server there is a problem with rendering chunks on every skywars/bedwars map which has a lot of void chunks,but our main hub world is loading just fine. We are using the build with commit 0ad2e64, newest bungeecord,spigot 1.8.8 and ProtocolLib.

**Comment by wow4201** [comment] 2016-03-03 22:51
Something important I've noticed is that, All servers that have problems are ones that are in the sky. Like the world is blank. (SkyWars, SkyBlock ect...)

**Comment by wow4201** [comment] 2016-03-03 23:09
To reproduce generate a world using "WickedSkyWars" generator.

Here is code to do so.
http://pastebin.com/Ab57LYUf

Here is the WickedSkyWars Generator Code
http://pastebin.com/jcUC5AJD

Here is WickedSkyWars plugin
https://www.spigotmc.org/resources/wickedskywars.556/download?version=18058

This isn't limited to skywars, but any server/plugin that produced a world with similar WorldGenerator Code

**Comment by themanwithaplan2** [comment] 2016-03-04 01:16
I have experienced this issue myself, yesterday I installed via version and my hub chunks started glitching out and a ton of areas became invisible, I was able to fix this by making a completely new hub map and creating a new world. It's worth noting that my previous broken hub was in a void world whereas this new one is in a regular grass flatworld

**Comment by Paulomart** [comment] 2016-03-04 06:00
This also happens in newly generated normal world's. As stated by @SanderGielisse this might be corrupt Packets. The question is then why can the client even render them (outlines).

**Comment by wow4201** [comment] 2016-03-04 06:10
Where did SanderGielisse state this? This only happens for me in worlds generated as void.

**Comment by Paulomart** [comment] 2016-03-04 06:15
That the packets wore corrupt. See above. We also have the same problem with glowstone++, but in 1.8. So I doubt the cause of this are the new packets.

**Comment by wow4201** [comment] 2016-03-04 07:01
Throwing out there that in a void world, the only difference is that there's nothing to throw shadows down onto.

**Comment by gigosaurus** [comment] 2016-03-04 08:04
This only seems to happen with chunk sections that have more than 4 Bits Per Block (basically any 16x16x16 area which contains more than 16 different types of blocks). I have yet to see a 4 BPB chunk section render incorrectly.

**Comment by wow4201** [comment] 2016-03-04 08:16
> This only seems to happen with chunk sections that have more than 4 Bits Per Block (basically any 16x16x16 area which contains more than 16 different types of blocks). I have yet to see a 4 BPB chunk section render 


When I worldedit everything grass, same thing.

**Comment by MylesIsCool** [comment] 2016-03-04 08:28
@gigosaurus This issue may be to do with the bitmask, as for a certain bit mask we detect as unload chunks?

**Comment by haelexuis** [comment] 2016-03-04 10:04
I have CleanroomGenerator and I have same problem with chunks

**Comment by SanderGielisse** [comment] 2016-03-04 18:11
Had exactly this same problem in a 1.9 Vanilla server. Neither the client or the server had been modified. Starting to get the idea it might be a client-sided issue.

**Comment by MylesIsCool** [comment] 2016-03-04 20:06
Re-opened as this is an issue.

**Comment by MylesIsCool** [comment] 2016-03-04 22:03
Fixed in 0.5+

**Closed by MylesIsCool** 2016-03-04 22:03 UTC
