### ISSUE TITLE
Double interact

### ISSUE THREAD

**Issue by concuncan** [MylesIsCool/ViaVersion#416] opened 2016-06-04 11:12 UTC
### What version of ViaVersion are you using? Type /ver viaversion
0.8.4
### What version of Spigot are you using? Type /ver
git-Spigot-5f38d38-18fbb24 - 1.8.8-30.1-SNAPSHOT.
### What plugins are you using? Type /plugins
ViaVersion, ProtocolLib and custom plugins.
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Yes, a modified version of BungeeCord.
### How does this error happen? login? Using an item? 
ProtocolLib still recieves an interact packet two times.
### Is there an error in the console? Use pastebin.com. Is there a kick message?
No.

**Comment by Matsv** [comment] 2016-06-04 12:55
The problem is with the new USE_ITEM packet. By canceling the USE_ITEM packet if the block placement packet was sent within 50 ms, it's breaking stuff like fishing, opening chests etc.

I recommend you using the player interact event, or checking if the packet was sent in the same tick

**Comment by Matsv** [comment] 2016-06-04 21:21
I'm closing this issue.

*why?*
This will be too complex and create more bugs than it'll fix. It'll not happen if you use the official spigot/bukkit events API.

**Closed by Matsv** 2016-06-04 21:21 UTC
