### ISSUE TITLE
Really Bad Servercrash-Bug

### ISSUE THREAD

**Issue by DatRobinPlays** [MylesIsCool/ViaVersion#378] opened 2016-04-27 17:15 UTC
### What version of ViaVersion are you using? Type /ver viaversion
0.7.9
### What version of Spigot are you using? Type /ver
1.8.8
### What plugins are you using? Type /plugins
too much (65 ^^)
**EDIT:** ![Plugins](https://cloud.githubusercontent.com/assets/18705052/14863727/382b0118-0cb7-11e6-9855-22159e517b64.png)
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord 1.9
### How does this error happen? login? Using an item? 

!! If I take on an elytra to the body slot and then switch my client to 1.8.x then the server crashes. :( Please fix it soon!!!!! 

### Is there an error in the console? Use pastebin.com. Is there a kick message?
only that the server closed

-- skype: haeHnchenkeulenserver / datrobinplays@gmail.com
please contact me with skype or email ^^

**Comment by DatRobinPlays** [comment] 2016-04-27 17:16
PLEASE FIX IT ^^

**Comment by MylesIsCool** [comment] 2016-04-27 17:22
Elytras aren't implemented, we suggest not trying to use them.

**Comment by DatRobinPlays** [comment] 2016-04-27 17:23
the problem is my plotworld (datrobinplays.de)

**Comment by DatRobinPlays** [comment] 2016-04-27 17:29
Will you fix it very soon, please?

**Comment by MylesIsCool** [comment] 2016-04-27 17:55
Can't replicate. Perhaps it'd be useful if you weren't lazy and actually filled in the plugin list so we can attempt to find the cause, or provide an error from the server.

**Comment by DatRobinPlays** [comment] 2016-04-27 18:01
Pls join my server in the next 5 minutes. You can look yourself. DatRobinPlays.de

**Comment by Matsv** [comment] 2016-04-27 18:19
We can't help you if you don't give us more information, for example, plugins, crash reports, server log etc.

**Comment by DatRobinPlays** [comment] 2016-04-27 18:21
Because of this I told you to Come to my server^^ (65 plugins is a Lot to write down)

**Comment by Matsv** [comment] 2016-04-27 18:22
We sadly need more then only plugins to be able to help you, you can make a screenshot of your plugins? :wink:

**Comment by HunterGPlays** [comment] 2016-04-27 18:22
Do /plugins and take a screenshot

-----Original Message-----

**Comment by DatRobinPlays** [comment] 2016-04-27 18:24
Can you add me pls on Skype for faster contact?  Haehnchenkeulenserver. Dont forget the second h.

**Comment by DatRobinPlays** [comment] 2016-04-27 18:33
![2016-04-27_20 31 08](https://cloud.githubusercontent.com/assets/18705052/14863727/382b0118-0cb7-11e6-9855-22159e517b64.png)
ok, I'll try to do the error again ^^ :(

**Comment by DatRobinPlays** [comment] 2016-04-27 18:40
...Tomorow: my PC is 'glitching :I

**Comment by Matsv** [comment] 2016-05-05 16:08
@DatRobinPlays Are you still having this issue?

**Comment by DatRobinPlays** [comment] 2016-05-05 17:34
I have completely servrr buggs - my bungeecord unhooks randomly from my
mainserver. I have to fix this First.
Am 05.05.2016 18:08 schrieb "Mats" <notifications@github.com>:

**Comment by MylesIsCool** [comment] 2016-05-10 15:23
Closing this issue, in the future provide all information. We won't login to your servers as we don't have the time, and provide as much info as possible.

**Closed by MylesIsCool** 2016-05-10 15:23 UTC
Labels: Issue Template
