### ISSUE TITLE
Client Crashes (plugin manager is removed and it still doesn't work)

### ISSUE THREAD

**Issue by johnsoncui02** [MylesIsCool/ViaVersion#579] opened 2016-11-21 23:18 UTC
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No BungeeCord. 1.10.2 server trying to get 1.11 to connect. 

### How does this error happen? login? Using an item? 
After entering the server with this plugin with the newest version. The server spigot version is 1.10.2

### Is there an error in the console? Use pastebin.com. Is there a kick message?
---- Minecraft Crash Report ----

// Don't be sad. I'll do better next time, I promise!

Time: 11/21/16 3:11 PM
Description: Ticking block entity

java.lang.IllegalArgumentException: Cannot get property atw{name=facing, clazz=class cv, values=[down, up, north, south, west, east]} as it does not exist in atk{block=minecraft:air, properties=[]}
	at atk$a.c(SourceFile:166)
	at atd.j(SourceFile:119)
	at atd.f(SourceFile:130)
	at atd.F_(SourceFile:308)
	at ajq.k(SourceFile:1484)
	at beq.t(SourceFile:1649)
	at beq.av(SourceFile:967)
	at beq.a(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:124)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at atk$a.c(SourceFile:166)
	at atd.j(SourceFile:119)
	at atd.f(SourceFile:130)
	at atd.F_(SourceFile:308)

-- Block entity being ticked --
Details:
	Name: minecraft:piston // atd
	Block type: ID #36 (tile.null // atc)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (30,129,1100), Chunk: (at 14,8,12 in 1,68; contains blocks 16,0,1088 to 31,255,1103), Region: (0,2; contains chunks 0,64 to 31,95, blocks 0,0,1024 to 511,255,1535)
	Actual block type: ID #36 (tile.null // atc)
	Actual block data value: 4 / 0x4 / 0b0100
Stacktrace:
	at ajq.k(SourceFile:1484)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [bpq['CornChowderSoup'/1594, l='MpServer', x=7.83, y=120.00, z=1070.56], bpr['0818'/422, l='MpServer', x=12.99, y=127.00, z=1070.62]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-55,191,349), Chunk: (at 9,11,13 in -4,21; contains blocks -64,0,336 to -49,255,351), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 14172541 game time, 14632129 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 91 total; [bpq['CornChowderSoup'/1594, l='MpServer', x=7.83, y=120.00, z=1070.56], zo['Creeper'/512, l='MpServer', x=-37.94, y=142.00, z=1054.57], aan['Zombie'/514, l='MpServer', x=-40.50, y=142.00, z=1055.50], aan['Zombie'/515, l='MpServer', x=-33.37, y=132.93, z=1057.38], aaf['Skeleton'/518, l='MpServer', x=-33.70, y=126.66, z=1058.37], bpr['0818'/422, l='MpServer', x=12.99, y=127.00, z=1070.62], aaf['Skeleton'/520, l='MpServer', x=-34.52, y=140.06, z=1055.26], acc['Minecart with Hopper'/522, l='MpServer', x=-15.14, y=119.06, z=1109.87], zo['Creeper'/1039, l='MpServer', x=-37.29, y=142.50, z=1054.98], aaf['Skeleton'/789, l='MpServer', x=30.67, y=121.00, z=1080.50], aaf['Skeleton'/795, l='MpServer', x=-26.50, y=142.00, z=1053.30], aaf['Skeleton'/796, l='MpServer', x=-24.50, y=142.00, z=1061.50], aaf['Skeleton'/546, l='MpServer', x=-37.70, y=142.00, z=1051.41], zi['item.item.reeds'/1573, l='MpServer', x=29.85, y=128.00, z=1091.03], bpr['0818'/422, l='MpServer', x=12.99, y=127.00, z=1070.62], wx['Cow'/423, l='MpServer', x=11.91, y=123.00, z=1055.47], zo['Creeper'/935, l='MpServer', x=-34.57, y=140.56, z=1056.49], wx['Cow'/424, l='MpServer', x=11.45, y=123.00, z=1056.55], xe['Sheep'/425, l='MpServer', x=-12.37, y=121.00, z=1058.82], aaf['Skeleton'/1577, l='MpServer', x=-35.50, y=142.00, z=1054.50], xb['Pig'/426, l='MpServer', x=10.46, y=121.00, z=1048.74], yw['Armor Stand'/427, l='MpServer', x=-8.50, y=120.00, z=1064.50], yw['Armor Stand'/428, l='MpServer', x=-6.50, y=114.00, z=1068.50], yw['Armor Stand'/429, l='MpServer', x=-6.50, y=120.00, z=1064.50], ww['Chicken'/430, l='MpServer', x=-15.25, y=121.00, z=1056.34], ww['Chicken'/432, l='MpServer', x=8.65, y=121.00, z=1055.72], wx['Cow'/433, l='MpServer', x=-19.89, y=121.00, z=1062.04], xe['Sheep'/434, l='MpServer', x=-13.28, y=121.00, z=1056.47], xe['Sheep'/435, l='MpServer', x=-5.75, y=121.00, z=1060.50], ww['Chicken'/436, l='MpServer', x=-13.14, y=121.00, z=1061.54], ww['Chicken'/437, l='MpServer', x=-12.50, y=121.00, z=1063.24], aan['Zombie'/821, l='MpServer', x=-29.92, y=142.00, z=1053.57], xe['Sheep'/438, l='MpServer', x=0.23, y=121.00, z=1050.52], xe['Sheep'/440, l='MpServer', x=-11.02, y=121.00, z=1057.30], xd['Rabbit'/441, l='MpServer', x=-8.69, y=121.23, z=1056.22], wx['Cow'/442, l='MpServer', x=-16.40, y=121.00, z=1054.18], xe['Sheep'/443, l='MpServer', x=-15.60, y=121.00, z=1061.52], xe['Sheep'/444, l='MpServer', x=5.53, y=121.00, z=1061.19], xe['Sheep'/445, l='MpServer', x=0.46, y=121.00, z=1061.88], zi['item.item.egg'/1213, l='MpServer', x=-16.19, y=121.00, z=1055.04], aan['Zombie'/1469, l='MpServer', x=-30.50, y=142.00, z=1050.50], ww['Chicken'/446, l='MpServer', x=-9.19, y=121.00, z=1057.19], aas['Villager'/447, l='MpServer', x=-4.62, y=121.00, z=1062.50], xd['Rabbit'/448, l='MpServer', x=-6.77, y=121.00, z=1061.53], xb['Pig'/450, l='MpServer', x=11.29, y=121.00, z=1055.33], xn['Horse'/451, l='MpServer', x=14.92, y=121.00, z=1049.09], xe['Sheep'/452, l='MpServer', x=7.87, y=121.00, z=1055.64], ww['Chicken'/453, l='MpServer', x=-11.15, y=121.00, z=1050.92], xd['Rabbit'/454, l='MpServer', x=5.67, y=121.00, z=1048.67], xe['Sheep'/455, l='MpServer', x=-11.62, y=121.00, z=1055.49], zi['item.item.egg'/456, l='MpServer', x=-7.35, y=121.00, z=1055.68], xn['Horse'/457, l='MpServer', x=-5.12, y=121.00, z=1049.05], xd['Rabbit'/458, l='MpServer', x=-8.82, y=121.00, z=1061.83], ww['Chicken'/459, l='MpServer', x=-17.84, y=121.00, z=1054.81], ww['Chicken'/460, l='MpServer', x=-16.78, y=121.00, z=1062.49], wx['Cow'/461, l='MpServer', x=-2.81, y=121.00, z=1053.62], xb['Pig'/462, l='MpServer', x=-1.77, y=121.00, z=1057.10], zi['item.item.egg'/847, l='MpServer', x=-4.53, y=121.00, z=1061.17], xd['Rabbit'/463, l='MpServer', x=-18.19, y=121.00, z=1050.93], aas['Villager'/464, l='MpServer', x=-10.46, y=121.00, z=1063.09], ww['Chicken'/465, l='MpServer', x=-19.18, y=121.00, z=1055.47], wx['Cow'/466, l='MpServer', x=-4.65, y=121.00, z=1060.21], aan['Zombie'/1493, l='MpServer', x=-37.50, y=142.00, z=1061.50], aaf['Skeleton'/471, l='MpServer', x=-31.27, y=142.00, z=1063.75], zo['Creeper'/473, l='MpServer', x=-30.50, y=140.23, z=1058.68], zo['Creeper'/474, l='MpServer', x=-27.21, y=142.00, z=1060.83], aaf['Skeleton'/477, l='MpServer', x=-28.51, y=142.00, z=1064.54], aaf['Skeleton'/478, l='MpServer', x=39.51, y=121.00, z=1068.32], aas['Villager'/482, l='MpServer', x=-14.93, y=121.00, z=1062.52], xn['Horse'/483, l='MpServer', x=-10.34, y=121.00, z=1048.69], xd['Rabbit'/484, l='MpServer', x=-6.81, y=121.00, z=1047.94], xd['Rabbit'/485, l='MpServer', x=-19.86, y=121.00, z=1048.34], zo['Creeper'/486, l='MpServer', x=-26.50, y=142.00, z=1054.71], aaf['Skeleton'/488, l='MpServer', x=-29.20, y=142.00, z=1056.10], aaf['Skeleton'/489, l='MpServer', x=-30.88, y=142.00, z=1055.67], zi['item.item.reeds'/492, l='MpServer', x=29.51, y=140.00, z=1091.87], zq['Enderman'/494, l='MpServer', x=-41.63, y=142.00, z=1061.73], aaf['Skeleton'/495, l='MpServer', x=-40.67, y=142.50, z=1061.40], zo['Creeper'/496, l='MpServer', x=-41.70, y=142.00, z=1062.44], aan['Zombie'/498, l='MpServer', x=-40.86, y=142.00, z=1060.60], aan['Zombie'/499, l='MpServer', x=-41.70, y=142.00, z=1059.98], zi['item.item.egg'/628, l='MpServer', x=-8.71, y=121.00, z=1061.07], zo['Creeper'/501, l='MpServer', x=-35.31, y=142.00, z=1061.28], zq['Enderman'/502, l='MpServer', x=-37.50, y=142.00, z=1065.50], aaf['Skeleton'/503, l='MpServer', x=-36.50, y=142.00, z=1064.50], aas['Villager'/504, l='MpServer', x=7.44, y=120.94, z=1107.51], acc['Minecart with Hopper'/505, l='MpServer', x=7.37, y=119.06, z=1110.80], zo['Creeper'/634, l='MpServer', x=-25.50, y=142.00, z=1053.50], aas['Villager'/507, l='MpServer', x=-11.56, y=120.94, z=1110.66], acc['Minecart with Hopper'/510, l='MpServer', x=-1.68, y=119.06, z=1106.51], aan['Zombie'/511, l='MpServer', x=-37.01, y=142.50, z=1050.18]]
	Retry entities: 0 total; []
	Server brand: Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at bno.a(SourceFile:365)
	at beq.b(SourceFile:2536)
	at beq.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:124)

-- System Details --
Details:
	Minecraft Version: 1.11
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 140614792 bytes (134 MB) / 259792896 bytes (247 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: 1.11

**Comment by MylesIsCool** [comment] 2016-11-22 15:59
Duplicate of #570

**Closed by MylesIsCool** 2016-11-22 15:59 UTC
