### ISSUE TITLE
Bossbar error in viaversion bungeecord

### ISSUE THREAD

**Issue by maxw2000** [MylesIsCool/ViaVersion#719] opened 2017-07-25 14:52 UTC
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/979ad57137c71ea34a304174b15f7fc8

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Bungeecord(waterfall)
serverlistplus
viaversion
advancedban

### How does this error happen? login? Using an item? 
if you join on a server with a bossbar and join a server with no bossbar it kicks you in version 1.9+ on a 1.8.8 server

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/7w1Rgqea

**Comment by Matsv** [comment] 2017-07-29 10:50
I'm unable to reproduce this issue.
Could you try if this happens for you with the [latest normal BungeeCord](https://ci.md-5.net/job/BungeeCord/lastSuccessfulBuild/artifact/bootstrap/target/BungeeCord.jar)?

**Comment by maxw2000** [comment] 2017-08-05 12:48
i have tried it but it still does not work for me

**Comment by MylesIsCool** [comment] 2017-08-05 12:51
In what way does it not work? Does the ViaVersion error still occur?

Provides logs etc.

**Comment by maxw2000** [comment] 2017-08-05 12:53
it still give errors in the logs
https://pastebin.com/yrYKxSMd

**Comment by MylesIsCool** [comment] 2017-09-29 13:14
I'm going to close this issue because unfortunately, we're not going to solve it without a constant method to reproduce. If anyone can provide a method to consistently reproduce etc then it would be something that we can get fixed.

**Closed by MylesIsCool** 2017-09-29 13:14 UTC
Labels: Can't Reproduce... Yet!
