### ISSUE TITLE
Random disconnect [1.8+] Clients

### ISSUE THREAD

**Issue by jooster11** [MylesIsCool/ViaVersion#368] opened 2016-04-21 16:35 UTC
Using the last version (0.7.8)

1.8.8-R0.1-Snapshot (243 versions behind)

### What plugins are you using? Type /plugins

Using the last bungeecord update from 11 April.

Since today random people kicked out of the server with the reason: [Proxy] Lost connection to the server. We've already looked into our bungeecord but there is nothing wrong with it. Only our main-lobbies are running currently the last viaversion update, and yes. Only people in the lobby will be kicked whole the time. We think this is caused by viaversion.

Nope, no error or anything weird else in the console.

**Comment by Matsv** [comment] 2016-04-21 16:49
Hm maybe the same issue as #367, could you please follow the issue template and post your plugins.

**Comment by fabien91** [comment] 2016-04-21 19:01
Hi,
Random people are disconnect on my server with this message since the last update of viaversion

![randomdisconnect](https://cloud.githubusercontent.com/assets/5675697/14720961/2853ef46-0804-11e6-8e64-934eb673394a.jpg)

**Comment by MylesIsCool** [comment] 2016-04-21 19:33
@fabien91 Can you post plugin list etc.

**Comment by fabien91** [comment] 2016-04-22 09:25
@MylesIsCool 
![pl](https://cloud.githubusercontent.com/assets/5675697/14737543/e57b0d66-087c-11e6-8ff5-b5f6865bc849.png)

**Comment by MylesIsCool** [comment] 2016-04-22 12:31
@fabien91 Are you using BungeeCord

**Comment by fabien91** [comment] 2016-04-22 14:17
@MylesIsCool yes

**Comment by MylesIsCool** [comment] 2016-04-22 14:26
@fabien91 There is a bungeecord bug I'm hoping to get patched to do with arrows crashing players on certain worlds, just waiting for it to be pulled.

**Comment by fabien91** [comment] 2016-04-22 14:32
Ok thank's

**Comment by MylesIsCool** [comment] 2016-04-23 23:41
https://github.com/SpigotMC/BungeeCord/commit/0b554be10adc4b19f1a08cf29017ef5d7ff26395

New version should fix random DCs on for 1.8 clients.

**Comment by wow4201** [comment] 2016-04-25 21:01
0.7.9
BungeeCord 1150 (Latest)



Every 5 minutes or so

_13:54:14 [SEVERE] [NoHaxJustNormal] <-> DownstreamBridge <-> [factions18] - encountered exception
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): SlicedAbstractByteBuf(ridx: 0, widx: 0, cap: 0/0, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2, widx: 2, cap: 112))
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): SlicedAbstractByteBuf(ridx: 0, widx: 0, cap: 0/0, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2, widx: 2, cap: 112))
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1178)
        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:587)
        at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:89)
        at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:79)
        at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:28)
        at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:10)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
        ... 20 more
_

**Comment by MylesIsCool** [comment] 2016-04-25 21:03
@wow4201 First, use pastebin. Second you're using a plugin that is doing something wrong it looks like.

**Comment by wow4201** [comment] 2016-04-25 21:12
http://pastebin.com/QiXjZL7d

Why does it look like that?

**Comment by MylesIsCool** [comment] 2016-04-25 21:13
@wow4201 " Second you're using a plugin that is doing something wrong it looks like. ", usually means your using a plugin that modifies packet data and doesn't let it cancel properly.

**Comment by wow4201** [comment] 2016-04-25 21:16
Is it possible to know what packet ENUM it's modifying based on that pastebin?

**Comment by MylesIsCool** [comment] 2016-04-25 21:24
@wow4201 No, but if you can replicate with 1 player on localhost, /viaver debug will usually help.

**Comment by MylesIsCool** [comment] 2016-04-27 16:15
Closing, if you have same issue open a new ticket.

**Closed by MylesIsCool** 2016-04-27 16:15 UTC
