### ISSUE TITLE
Signs

### ISSUE THREAD

**Issue by melerpe** [MylesIsCool/ViaVersion#380] opened 2016-04-28 12:28 UTC
### What version of ViaVersion are you using? Type /ver viaversion
0.7.9
### What version of Spigot are you using? Type /ver
1.8.8
### What plugins are you using? Type /plugins

![](https://i.gyazo.com/9a15179a5b5a78a73b969873b38011bf.png)

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No bungee
Newest of all plugins
### How does this error happen? login? Using an item? 
Randomly some signs dont workd
### Is there an error in the console? Use pastebin.com. Is there a kick message?

Nope

**Comment by Matsv** [comment] 2016-04-28 14:27
Duplicate of #352

**Closed by Matsv** 2016-04-28 14:27 UTC

**Comment by melerpe** [comment] 2016-04-28 15:28
MVDWPLACEHOLDERS is not used, so this is not really a duplicate i think!
This happens randomly with every sing on 1.9.

**Comment by Matsv** [comment] 2016-04-28 15:29
Also happens with ProtocolLib, title was wrong.
