### ISSUE TITLE
map in frames different version rotation (?)desync(?)

### ISSUE THREAD

**Issue by wulfwuud** [MylesIsCool/ViaVersion#745] opened 2017-09-10 21:18 UTC
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Waterfall last build
as for plugins
only custom coded stuff and skinrestorer

### How does this error happen? login? Using an item? 
everytiem

### Is there an error in the console? Use pastebin.com. Is there a kick message?
nope

https://imgur.com/a/9x6jO
1 screen made on 1.8.9 optifine client
2 screen made on 1.12 optifine client
I'm using https://github.com/m0bYczE/FramePicture for pic's however same problem with AnimatedFrames

**Comment by MylesIsCool** [comment] 2017-09-10 21:25
Could you fill out all the information in the issue (specifically the "/viaversion dump")

**Comment by wulfwuud** [comment] 2017-09-10 21:38
@MylesIsCool 
Ok. rdy

**Comment by MylesIsCool** [comment] 2017-09-11 10:36
I can't reproduce this on a vanilla client.

I'm using MapManager, AnimatedFrames and tested on 1.12.1 client & 1.8.8 client (both show correctly).

Could you test with vanilla client without optifine?

**Comment by wulfwuud** [comment] 2017-09-11 11:20
yeah it is definately not a viaversion problem
caused by my modified spigot

**Comment by MylesIsCool** [comment] 2017-09-11 11:21
Ah fair enough :), I'll close this issue as there's not much else I can help with in regards to it. I wish you luck in solving the issue.

**Closed by MylesIsCool** 2017-09-11 11:21 UTC
Labels: Can't Reproduce... Yet!
