### ISSUE TITLE
 Players getting error on login if disconnected during login.

### ISSUE THREAD

**Issue by VoidWhisperer** [MylesIsCool/ViaVersion#515] opened 2016-10-14 14:55 UTC
### What is the output link of /viaversion dump?
http://hastebin.com/tuxivagopo.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Lilypad

### How does this error happen? login? Using an item? 
Any circumstance that would cause a player to get disconnected during login (in this case a player being banned)

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No

Other information: I grabbed the 0.9.10 version off github and added a line of code into the fixJson() function of the 1_9to1_8 converter to print the json before it is converted and noticed something off -
[Picture](http://v-l.pw/f4dd2602.png)

**Comment by MylesIsCool** [comment] 2016-10-14 15:25
Have you tried turning on force json transform in the config?

Otherwise you're not sending json. (Force json transform is our workaround but realistically the protocol is json)

**Comment by VoidWhisperer** [comment] 2016-10-14 17:12
@MylesIsCool That did not fix it, it's still returning this when I attempt to log in:
[Error](http://v-l.pw/8d334f52.png)

**Comment by MylesIsCool** [comment] 2016-10-14 17:16
@VoidWhisperer Get whatever plugin is sending bad json to fix themselves? (LiteBans?)

**Comment by danjb2000** [comment] 2016-10-14 17:21
@MylesIsCool This error is happening with any plugin sending a dis-connect message to the client. Even if necessarily not using JSON.

We've even wrote a plugin ourselves that DC's people with a message to test it.

**Comment by VoidWhisperer** [comment] 2016-10-14 17:26
@MylesIsCool Any plugin that disconnects someone during the LOGIN part of the protocol, before they join the server (IE during asyncplayerpreloginevent) and uses json will result in this error. It's most definitely an issue with ViaVersion.

**Comment by MylesIsCool** [comment] 2016-10-14 17:27
@danjb2000 @VoidWhisperer If you could provide an example of a crash log / the same output (using the system.outs) as above when using this with proper json it would be appreciated.

**Comment by VoidWhisperer** [comment] 2016-10-14 17:28
@MylesIsCool What output in specific do you want? (Sorry, just trying to clarify.) I can try to get it to you then.

**Comment by MylesIsCool** [comment] 2016-10-14 17:29
@VoidWhisperer just the printing of the message as well as the code you used to produce it (printing from fixJson())

**Comment by VoidWhisperer** [comment] 2016-10-14 17:32
@MylesIsCool Do you want the code that is setting the kick reason during the asyncplayerpreloginevent or just the modified fixJson() function?

**Comment by MylesIsCool** [comment] 2016-10-14 17:33
@VoidWhisperer The code for the kick reason + the output of the modified fixJson when used with that code

**Comment by MylesIsCool** [comment] 2016-10-14 21:48
Going to lock this until it's fixed. The issue is we don't handle the disconnect packet in handshake and we should to prevent bad json from being sent.

**Comment by MylesIsCool** [comment] 2016-10-14 22:08
Should be fixed now, if any issues just reply

**Closed by MylesIsCool** 2016-10-14 22:08 UTC
