### ISSUE TITLE
End portal block is invisible for 1.10.2 players

### ISSUE THREAD

**Issue by haelexuis** [MylesIsCool/ViaVersion#451] opened 2016-06-23 19:34 UTC
### What version of Spigot are you using? 1.9

This is end portal, https://cdn.pbrd.co/images/1U8IhY4J.png.. I belive, you don't need any description :D

**Comment by Matsv** [comment] 2016-06-23 19:49
Please use the issue template. https://github.com/MylesIsCool/ViaVersion/blob/master/ISSUE_TEMPLATE.md

**Comment by haelexuis** [comment] 2016-06-24 00:35
But.. it is texture o.O you don't need any info, try it and send me screen where is portal on minecraft 1.10.2

**Comment by Matsv** [comment] 2016-06-24 06:40
I can't reproduce this with spigot 1.9.4. That's why I ask for more info.

**Comment by Matsv** [comment] 2016-06-24 07:01
Screenshot you asked for: https://fs.matsv.nl/media?id=w0wh7fbo

**Comment by haelexuis** [comment] 2016-06-25 12:51
Ah, I have 1.9 R1..

**Comment by Matsv** [comment] 2016-06-25 12:52
Could you give me the full output of /ver ViaVersion and /ver

**Comment by MylesIsCool** [comment] 2016-06-25 15:58
Closing this as it's down to you using 1.9.2 which is not supported, watch the above pull request for progress.

This is a good reason why you should fill out the issue template.

**Closed by MylesIsCool** 2016-06-25 15:58 UTC
Labels: Can't Reproduce... Yet!, Issue Template
