### ISSUE TITLE
Invisble Bug

### ISSUE THREAD

**Issue by 8Marc8** [MylesIsCool/ViaVersion#267] opened 2016-03-23 08:35 UTC
### What version of ViaVersion are you using? Type /ver viaversion
0.6.7

### What version of Spigot are you using? Type /ver
git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
### What plugins are you using? Type /plugins
Its different to every Gameserver, always ProtocolLib, WorldEdit, Worldguard, HideStream and Multiverse
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Yes:
Party and Friends extended
Bungeeban
Bungeekick
Slashserver
### How does this error happen? login? Using an item? 
When a Player get teleported (for Example after a Death), he often gets invisible
### Is there an error in the console? Use pastebin.com. Is there a kick message?
No

Edit: I am using Java 7, maybe this causes the bug...

**Comment by 8Marc8** [comment] 2016-03-23 08:37
Edit: Maybe I should use Java 8... Could this cause the bug?

**Comment by HugoDaBosss** [comment] 2016-03-23 09:11
Probably related to #193

**Comment by 8Marc8** [comment] 2016-03-23 10:03
Yeah @HugoDaBoss
But there is no fix, too :-(
Same Problem...

**Comment by Matsv** [comment] 2016-03-23 10:11
@8Marc8 This is a minecraft or spigot glitch, I'll close it because this is not a viaversion bug. Try to search online to see if there are solutions to fix this :)

**Closed by Matsv** 2016-03-23 10:11 UTC

**Comment by 8Marc8** [comment] 2016-03-23 10:31
But @Matsv , its only happening with ViaVersion...

**Comment by Matsv** [comment] 2016-03-23 10:38
@8Marc8 Is it happening for 1.8 too?

**Comment by 8Marc8** [comment] 2016-03-23 10:49
@Matsv Yes, on both versions, but without viaversion the bug doenst appear.

**Comment by Matsv** [comment] 2016-03-23 10:53
@8Marc8 The problem is, ViaVersion is not modifying the 1.8 client and server. We think it's technically impossible that we cause that bug for 1.8

**Comment by 8Marc8** [comment] 2016-03-23 10:56
Do you know such problems with AAC and ViaVersion?
My Friend installed it yesterday (AAC)
@Matsv

**Comment by Matsv** [comment] 2016-03-23 10:58
@8Marc8 Hm didn't it happen before AAC?

**Comment by 8Marc8** [comment] 2016-03-23 10:59
@Matsv I cant remember, but I'm sure that Bedwars never had the Problem before...

**Comment by Matsv** [comment] 2016-03-23 11:09
@8Marc8 Might be AAC, #193 was also using it. Could you try using this plugin without AAC and see if the problem still occurs?

**Comment by 8Marc8** [comment] 2016-03-23 11:10
Okay, will try out today :-)

**Comment by Matsv** [comment] 2016-03-23 11:12
Thanks :smile:

**Comment by 8Marc8** [comment] 2016-03-24 14:55
@Matsv The problem is solved ☺ I had a an old version of ProtocolLib, this caused the bugs. This is maybe the fix for #193 , too.

**Comment by Matsv** [comment] 2016-03-24 14:58
@8Marc8 good to hear that :+1: :
