### ISSUE TITLE
Random disconnects

### ISSUE THREAD

**Issue by MrBrikster** [MylesIsCool/ViaVersion#367] opened 2016-04-21 14:30 UTC
Version of plugin - 0.7.5

Spigot version: "This server is running CraftBukkit version git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)"

Plugins: PlayerHeads, MMCases, WorldEdit, SkinsModule, EmptyGenerator, CommandsDispatcher, ClearLag, PluginManagerReloaded, AutoMessage, Chairs, WorldBorder, RandomTP, TeleportSigns, WorldGuard, Multiverse-Core, NoCheatPlus, ItemFixer, SignEdit, PermissionsEx, SocketAPI, MMKeys, WGExtender, ViaVersion, CustomJoinItems, MineResetLite, Vault, UralClans, WorldeditRegions, Lores, CustomEnchantments, Backpacks, TabPrefix, MyPet, ChestShop, Essentials, Jobs, HolographicDisplays, LobbyParkour, Scavenger, LiteBans, Fe, ChestCommands, ChatEx, EssentialsSpawn, TitleManager

I am using bungeecord. Plugins: BungeeAuth (not public), SocketApi, CommandDispatcher, QuietCord, ServerInfo, SkinsRestorer, Yamler, BungeeRcon, BotFilter (not public).

Players get random disconnects if login from 1.9-1.9.2. (Image: http://imgur.com/1Rxq7hY)

There are no error logs (standart "Nickname lost connection: Disconnected" and "[Nickname] disconnected with: [Proxy] Lost connection to server.")

Sorry for my bad English. Thanks!

**Comment by Matsv** [comment] 2016-04-21 14:31
Duplicate of: #364 
It's fixed next version :)

**Comment by MrBrikster** [comment] 2016-04-21 14:38
Sorry, but there are disconnects are randomly, not on pressing key "F". Also, there are no errors in logs.

**Comment by Matsv** [comment] 2016-04-21 15:25
Please try the latest viaversion

**Comment by MrBrikster** [comment] 2016-04-21 16:04
I am now using latest version. About 3 minutes ago I got disconnect with old error (http://imgur.com/1Rxq7hY). Version of minecraft: 1.9.2). Thanks.

**Comment by Matsv** [comment] 2016-04-21 16:48
Thank you. Could you try turning on debug=true in server.properties? If there is something after that in the console, could you please post it here? :)

**Comment by MrBrikster** [comment] 2016-04-21 17:45
OK, debug is now true. I will post all errors.

**Comment by MrBrikster** [comment] 2016-04-21 17:51
Hm... I got the error: 
```
[20:50:31 WARN]: java.nio.channels.ClosedChannelException
[20:50:31 WARN]: java.nio.channels.ClosedChannelException
[20:50:31 WARN]: java.nio.channels.ClosedChannelException
[20:50:31 WARN]: java.nio.channels.ClosedChannelException
[20:50:31 INFO]: MrBrikster lost connection: Disconnected
```

**Comment by MylesIsCool** [comment] 2016-04-21 17:59
Try without plugins and see if it still happens primarily skin restorer.

**Comment by MrBrikster** [comment] 2016-04-21 18:13
I am now trying without Skinsrestorer skinsmodule for bukkit (skinsrestorer is working, but some functions are disabled)

**Comment by MrBrikster** [comment] 2016-04-22 12:28
It's not SkinsRestorer. I started server with SkinsRestorer without another plugins. I didn't disconnected.

**Comment by MylesIsCool** [comment] 2016-04-22 12:31
@MrBrikster Just because you tried with it on it's own doesn't mean there isn't a compatibility issue which means ViaVersion will work without it.

ViaVersion allows a whole separate version which SkinRestorer modifies it at a Bungee level some of the time (depending on your setup.). Hence me asking you to try without it.

**Comment by MrBrikster** [comment] 2016-04-22 13:54
No... I removed SkinsRestorer from bungee and SkinsModule and got disconnect.

**Comment by MrBrikster** [comment] 2016-04-22 15:19
I think, the problem is holographicdisplays. I try to remove it.

**Comment by MrBrikster** [comment] 2016-04-22 16:32
Ooo... without holographic displays there are disconnects too.

**Comment by MrBrikster** [comment] 2016-04-23 09:23
I have a plugin, which add prefix to nick above player's head. Can it make disconnects?

**Comment by MrBrikster** [comment] 2016-04-23 14:54
OK, thanks! A plugin "LobbyParkour" made disconnects.

**Closed** 2016-04-24 17:24 UTC
