### ISSUE TITLE
ClassCastException when quitting

### ISSUE THREAD

**Issue by HugoDaBosss** [MylesIsCool/ViaVersion#274] opened 2016-03-25 22:45 UTC
### What version of ViaVersion are you using? Type /ver viaversion
0.6.7
### What version of Spigot are you using? Type /ver
CraftBukkit version git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
### What plugins are you using? Type /plugins
EssentialsX, Viaversion and ProtocolLib
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No
### How does this error happen? login? Using an item? 
Quit the game, only happened once though. I am not able to replicate this more times...
Was trying to replicate #273, got this. The error is similar to #273, there is just a difference in stacktrace because of TacoSpigot vs Spigot
### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/GED21r6i

**Comment by MylesIsCool** [comment] 2016-03-27 23:03
Dupe of #273 Closing so that we don't have more issues than one for bug.

**Closed by MylesIsCool** 2016-03-27 23:03 UTC
Labels: Can't Reproduce... Yet!
