### ISSUE TITLE
Hub Server Crashs every ~30 min (more users -> crash is sooner)

### ISSUE THREAD

**Issue by Bodoo** [MylesIsCool/ViaVersion#243] opened 2016-03-18 15:54 UTC
### What version of ViaVersion are you using? Type /ver viaversion
0.6.5
### What version of Spigot are you using? Type /ver
1.8.8
### What plugins are you using? Type /plugins
Plugins (21): LobbyBorder, bBansBukkitAPI, EchoPet, PermissionsEx, Buycraft, ViaVersion, LoadNetAPI, LobbySignSystem, ConnectionDebug, ProtocolLib, aaPool, GApi, NickAPI, General, Lobby18Upgrade, ChatLogAPI, Balloon, PetPlugin, VersionBlocker, BlockReload, DuelsLobby

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
newest BungeeCord
### How does this error happen? login? Using an item? 
We don't know
### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://hastebin.com/hotoquyowa.css

Some players get kicked with an error which looks like the exception message, but often the hub server just laggs for a few min Tps will fall until 10 and then crash

**Comment by HugoDaBosss** [comment] 2016-03-18 16:07
Duplicate of #149 #194 and #202

**Comment by HugoDaBosss** [comment] 2016-03-18 16:14
Some more details: Block digging is cancelled, so as soon as a player starts digging it will cancel, so actual block is not even broken, and thus the packet is not sent to the server

**Comment by MylesIsCool** [comment] 2016-03-20 16:47
Use 0.6.7, closing issue. Request reopen if still occurs.

**Closed by MylesIsCool** 2016-03-20 16:47 UTC
Labels: Duplicate
